/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.30.0**, built 2026-08-09T14:05:32.309Z
 *
 * The version of the OpenAPI document: 2.30.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing A2PBillingConsent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class A2PBillingConsentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for A2PBillingConsent
        //private A2PBillingConsent instance;

        public A2PBillingConsentTests()
        {
            // TODO uncomment below to create an instance of A2PBillingConsent
            //instance = new A2PBillingConsent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of A2PBillingConsent
        /// </summary>
        [Fact]
        public void A2PBillingConsentInstanceTest()
        {
            // TODO uncomment below to test "IsType" A2PBillingConsent
            //Assert.IsType<A2PBillingConsent>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Fact]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
