/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing ClickFunnelContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClickFunnelContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClickFunnelContact
        //private ClickFunnelContact instance;

        public ClickFunnelContactTests()
        {
            // TODO uncomment below to create an instance of ClickFunnelContact
            //instance = new ClickFunnelContact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClickFunnelContact
        /// </summary>
        [Fact]
        public void ClickFunnelContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClickFunnelContact
            //Assert.IsType<ClickFunnelContact>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PageId'
        /// </summary>
        [Fact]
        public void PageIdTest()
        {
            // TODO unit test for the property 'PageId'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Fact]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'WebinarAt'
        /// </summary>
        [Fact]
        public void WebinarAtTest()
        {
            // TODO unit test for the property 'WebinarAt'
        }

        /// <summary>
        /// Test the property 'WebinarLastTime'
        /// </summary>
        [Fact]
        public void WebinarLastTimeTest()
        {
            // TODO unit test for the property 'WebinarLastTime'
        }

        /// <summary>
        /// Test the property 'WebinarExt'
        /// </summary>
        [Fact]
        public void WebinarExtTest()
        {
            // TODO unit test for the property 'WebinarExt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }

        /// <summary>
        /// Test the property 'FunnelId'
        /// </summary>
        [Fact]
        public void FunnelIdTest()
        {
            // TODO unit test for the property 'FunnelId'
        }

        /// <summary>
        /// Test the property 'FunnelStepId'
        /// </summary>
        [Fact]
        public void FunnelStepIdTest()
        {
            // TODO unit test for the property 'FunnelStepId'
        }

        /// <summary>
        /// Test the property 'UnsubscribedAt'
        /// </summary>
        [Fact]
        public void UnsubscribedAtTest()
        {
            // TODO unit test for the property 'UnsubscribedAt'
        }

        /// <summary>
        /// Test the property 'CfUvid'
        /// </summary>
        [Fact]
        public void CfUvidTest()
        {
            // TODO unit test for the property 'CfUvid'
        }

        /// <summary>
        /// Test the property 'CartAffiliateId'
        /// </summary>
        [Fact]
        public void CartAffiliateIdTest()
        {
            // TODO unit test for the property 'CartAffiliateId'
        }

        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Fact]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }

        /// <summary>
        /// Test the property 'ShippingCity'
        /// </summary>
        [Fact]
        public void ShippingCityTest()
        {
            // TODO unit test for the property 'ShippingCity'
        }

        /// <summary>
        /// Test the property 'ShippingCountry'
        /// </summary>
        [Fact]
        public void ShippingCountryTest()
        {
            // TODO unit test for the property 'ShippingCountry'
        }

        /// <summary>
        /// Test the property 'ShippingState'
        /// </summary>
        [Fact]
        public void ShippingStateTest()
        {
            // TODO unit test for the property 'ShippingState'
        }

        /// <summary>
        /// Test the property 'ShippingZip'
        /// </summary>
        [Fact]
        public void ShippingZipTest()
        {
            // TODO unit test for the property 'ShippingZip'
        }

        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Fact]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }

        /// <summary>
        /// Test the property 'AffiliateId'
        /// </summary>
        [Fact]
        public void AffiliateIdTest()
        {
            // TODO unit test for the property 'AffiliateId'
        }

        /// <summary>
        /// Test the property 'AffSub'
        /// </summary>
        [Fact]
        public void AffSubTest()
        {
            // TODO unit test for the property 'AffSub'
        }

        /// <summary>
        /// Test the property 'AffSub2'
        /// </summary>
        [Fact]
        public void AffSub2Test()
        {
            // TODO unit test for the property 'AffSub2'
        }

        /// <summary>
        /// Test the property 'CfAffiliateId'
        /// </summary>
        [Fact]
        public void CfAffiliateIdTest()
        {
            // TODO unit test for the property 'CfAffiliateId'
        }

        /// <summary>
        /// Test the property 'ContactProfile'
        /// </summary>
        [Fact]
        public void ContactProfileTest()
        {
            // TODO unit test for the property 'ContactProfile'
        }

        /// <summary>
        /// Test the property 'VarTimeZone'
        /// </summary>
        [Fact]
        public void VarTimeZoneTest()
        {
            // TODO unit test for the property 'VarTimeZone'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'CompanyIndustry'
        /// </summary>
        [Fact]
        public void CompanyIndustryTest()
        {
            // TODO unit test for the property 'CompanyIndustry'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'GaClientId'
        /// </summary>
        [Fact]
        public void GaClientIdTest()
        {
            // TODO unit test for the property 'GaClientId'
        }

        /// <summary>
        /// Test the property 'GaMeasurementId'
        /// </summary>
        [Fact]
        public void GaMeasurementIdTest()
        {
            // TODO unit test for the property 'GaMeasurementId'
        }

        /// <summary>
        /// Test the property 'FunnelName'
        /// </summary>
        [Fact]
        public void FunnelNameTest()
        {
            // TODO unit test for the property 'FunnelName'
        }

        /// <summary>
        /// Test the property 'HttpReferrer'
        /// </summary>
        [Fact]
        public void HttpReferrerTest()
        {
            // TODO unit test for the property 'HttpReferrer'
        }

        /// <summary>
        /// Test the property 'LandingPage'
        /// </summary>
        [Fact]
        public void LandingPageTest()
        {
            // TODO unit test for the property 'LandingPage'
        }
    }
}
