/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing EntityTooLarge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntityTooLargeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntityTooLarge
        //private EntityTooLarge instance;

        public EntityTooLargeTests()
        {
            // TODO uncomment below to create an instance of EntityTooLarge
            //instance = new EntityTooLarge();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntityTooLarge
        /// </summary>
        [Fact]
        public void EntityTooLargeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntityTooLarge
            //Assert.IsType<EntityTooLarge>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Stack'
        /// </summary>
        [Fact]
        public void StackTest()
        {
            // TODO unit test for the property 'Stack'
        }

        /// <summary>
        /// Test the property 'HttpErrorCode'
        /// </summary>
        [Fact]
        public void HttpErrorCodeTest()
        {
            // TODO unit test for the property 'HttpErrorCode'
        }

        /// <summary>
        /// Test the property 'TrackingCode'
        /// </summary>
        [Fact]
        public void TrackingCodeTest()
        {
            // TODO unit test for the property 'TrackingCode'
        }
    }
}
