/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing FetchInboundSMSByPage200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FetchInboundSMSByPage200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FetchInboundSMSByPage200Response
        //private FetchInboundSMSByPage200Response instance;

        public FetchInboundSMSByPage200ResponseTests()
        {
            // TODO uncomment below to create an instance of FetchInboundSMSByPage200Response
            //instance = new FetchInboundSMSByPage200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FetchInboundSMSByPage200Response
        /// </summary>
        [Fact]
        public void FetchInboundSMSByPage200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FetchInboundSMSByPage200Response
            //Assert.IsType<FetchInboundSMSByPage200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
