/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing MSAnalyticsMembershipTierAmountRefundedPartitionedByDate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MSAnalyticsMembershipTierAmountRefundedPartitionedByDateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MSAnalyticsMembershipTierAmountRefundedPartitionedByDate
        //private MSAnalyticsMembershipTierAmountRefundedPartitionedByDate instance;

        public MSAnalyticsMembershipTierAmountRefundedPartitionedByDateTests()
        {
            // TODO uncomment below to create an instance of MSAnalyticsMembershipTierAmountRefundedPartitionedByDate
            //instance = new MSAnalyticsMembershipTierAmountRefundedPartitionedByDate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MSAnalyticsMembershipTierAmountRefundedPartitionedByDate
        /// </summary>
        [Fact]
        public void MSAnalyticsMembershipTierAmountRefundedPartitionedByDateInstanceTest()
        {
            // TODO uncomment below to test "IsType" MSAnalyticsMembershipTierAmountRefundedPartitionedByDate
            //Assert.IsType<MSAnalyticsMembershipTierAmountRefundedPartitionedByDate>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
