/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing MSMerchantCreditHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MSMerchantCreditHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MSMerchantCreditHistory
        //private MSMerchantCreditHistory instance;

        public MSMerchantCreditHistoryTests()
        {
            // TODO uncomment below to create an instance of MSMerchantCreditHistory
            //instance = new MSMerchantCreditHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MSMerchantCreditHistory
        /// </summary>
        [Fact]
        public void MSMerchantCreditHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" MSMerchantCreditHistory
            //Assert.IsType<MSMerchantCreditHistory>(instance);
        }

        /// <summary>
        /// Test the property 'MemberIdentifier'
        /// </summary>
        [Fact]
        public void MemberIdentifierTest()
        {
            // TODO unit test for the property 'MemberIdentifier'
        }

        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Fact]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }

        /// <summary>
        /// Test the property 'CreditAmount'
        /// </summary>
        [Fact]
        public void CreditAmountTest()
        {
            // TODO unit test for the property 'CreditAmount'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'MerchantCreditID'
        /// </summary>
        [Fact]
        public void MerchantCreditIDTest()
        {
            // TODO unit test for the property 'MerchantCreditID'
        }

        /// <summary>
        /// Test the property 'MerchantID'
        /// </summary>
        [Fact]
        public void MerchantIDTest()
        {
            // TODO unit test for the property 'MerchantID'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
    }
}
