/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedWTMerchantCredits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedWTMerchantCreditsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedWTMerchantCredits
        //private PaginatedWTMerchantCredits instance;

        public PaginatedWTMerchantCreditsTests()
        {
            // TODO uncomment below to create an instance of PaginatedWTMerchantCredits
            //instance = new PaginatedWTMerchantCredits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedWTMerchantCredits
        /// </summary>
        [Fact]
        public void PaginatedWTMerchantCreditsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedWTMerchantCredits
            //Assert.IsType<PaginatedWTMerchantCredits>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
