/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActiveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive
        //private PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive instance;

        public PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActiveTests()
        {
            // TODO uncomment below to create an instance of PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive
            //instance = new PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive
        /// </summary>
        [Fact]
        public void PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActiveInstanceTest()
        {
            // TODO uncomment below to test "IsType" PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive
            //Assert.IsType<PickCreateStaticVoucherCampaignWithVoucherExcludeKeyofcreateStaticVoucherCampaignWithVoucherIsActive>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'ValueType'
        /// </summary>
        [Fact]
        public void ValueTypeTest()
        {
            // TODO unit test for the property 'ValueType'
        }

        /// <summary>
        /// Test the property 'DisplayValue'
        /// </summary>
        [Fact]
        public void DisplayValueTest()
        {
            // TODO unit test for the property 'DisplayValue'
        }

        /// <summary>
        /// Test the property 'MerchantsReferenceID'
        /// </summary>
        [Fact]
        public void MerchantsReferenceIDTest()
        {
            // TODO unit test for the property 'MerchantsReferenceID'
        }

        /// <summary>
        /// Test the property 'ValidOnlyAtPOSRegisterIDs'
        /// </summary>
        [Fact]
        public void ValidOnlyAtPOSRegisterIDsTest()
        {
            // TODO unit test for the property 'ValidOnlyAtPOSRegisterIDs'
        }

        /// <summary>
        /// Test the property 'PaymentDesignID'
        /// </summary>
        [Fact]
        public void PaymentDesignIDTest()
        {
            // TODO unit test for the property 'PaymentDesignID'
        }

        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Fact]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }

        /// <summary>
        /// Test the property 'ExpirationDateTime'
        /// </summary>
        [Fact]
        public void ExpirationDateTimeTest()
        {
            // TODO unit test for the property 'ExpirationDateTime'
        }

        /// <summary>
        /// Test the property 'SourceID'
        /// </summary>
        [Fact]
        public void SourceIDTest()
        {
            // TODO unit test for the property 'SourceID'
        }

        /// <summary>
        /// Test the property 'MemberID'
        /// </summary>
        [Fact]
        public void MemberIDTest()
        {
            // TODO unit test for the property 'MemberID'
        }

        /// <summary>
        /// Test the property 'OfferAmountCents'
        /// </summary>
        [Fact]
        public void OfferAmountCentsTest()
        {
            // TODO unit test for the property 'OfferAmountCents'
        }

        /// <summary>
        /// Test the property 'CellPhone'
        /// </summary>
        [Fact]
        public void CellPhoneTest()
        {
            // TODO unit test for the property 'CellPhone'
        }
    }
}
