/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        public ProductTests()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Fact]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" Product
            //Assert.IsType<Product>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'TitleFull'
        /// </summary>
        [Fact]
        public void TitleFullTest()
        {
            // TODO unit test for the property 'TitleFull'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'IconName'
        /// </summary>
        [Fact]
        public void IconNameTest()
        {
            // TODO unit test for the property 'IconName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Plans'
        /// </summary>
        [Fact]
        public void PlansTest()
        {
            // TODO unit test for the property 'Plans'
        }

        /// <summary>
        /// Test the property 'IsHourly'
        /// </summary>
        [Fact]
        public void IsHourlyTest()
        {
            // TODO unit test for the property 'IsHourly'
        }
    }
}
