/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.50.0**, built 2026-09-28T18:16:29.461Z
 *
 * The version of the OpenAPI document: 2.50.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTAutoResponderHitOutcome
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTAutoResponderHitOutcomeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTAutoResponderHitOutcome
        //private WTAutoResponderHitOutcome instance;

        public WTAutoResponderHitOutcomeTests()
        {
            // TODO uncomment below to create an instance of WTAutoResponderHitOutcome
            //instance = new WTAutoResponderHitOutcome();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTAutoResponderHitOutcome
        /// </summary>
        [Fact]
        public void WTAutoResponderHitOutcomeInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTAutoResponderHitOutcome
            //Assert.IsType<WTAutoResponderHitOutcome>(instance);
        }
    }
}
