/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTAuthenticationCheckSessionTokenStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTAuthenticationCheckSessionTokenStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTAuthenticationCheckSessionTokenStatusResponse
        //private WTAuthenticationCheckSessionTokenStatusResponse instance;

        public WTAuthenticationCheckSessionTokenStatusResponseTests()
        {
            // TODO uncomment below to create an instance of WTAuthenticationCheckSessionTokenStatusResponse
            //instance = new WTAuthenticationCheckSessionTokenStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTAuthenticationCheckSessionTokenStatusResponse
        /// </summary>
        [Fact]
        public void WTAuthenticationCheckSessionTokenStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTAuthenticationCheckSessionTokenStatusResponse
            //Assert.IsType<WTAuthenticationCheckSessionTokenStatusResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
