/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.0**, built 2026-07-08T17:05:52.109Z
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTConnectMoney
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTConnectMoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTConnectMoney
        //private WTConnectMoney instance;

        public WTConnectMoneyTests()
        {
            // TODO uncomment below to create an instance of WTConnectMoney
            //instance = new WTConnectMoney();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTConnectMoney
        /// </summary>
        [Fact]
        public void WTConnectMoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTConnectMoney
            //Assert.IsType<WTConnectMoney>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
    }
}
