/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTCustomerSearchByPhoneNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTCustomerSearchByPhoneNumberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTCustomerSearchByPhoneNumber
        //private WTCustomerSearchByPhoneNumber instance;

        public WTCustomerSearchByPhoneNumberTests()
        {
            // TODO uncomment below to create an instance of WTCustomerSearchByPhoneNumber
            //instance = new WTCustomerSearchByPhoneNumber();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTCustomerSearchByPhoneNumber
        /// </summary>
        [Fact]
        public void WTCustomerSearchByPhoneNumberInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTCustomerSearchByPhoneNumber
            //Assert.IsType<WTCustomerSearchByPhoneNumber>(instance);
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
    }
}
