/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTDiningCreateParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTDiningCreateParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTDiningCreateParams
        //private WTDiningCreateParams instance;

        public WTDiningCreateParamsTests()
        {
            // TODO uncomment below to create an instance of WTDiningCreateParams
            //instance = new WTDiningCreateParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTDiningCreateParams
        /// </summary>
        [Fact]
        public void WTDiningCreateParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTDiningCreateParams
            //Assert.IsType<WTDiningCreateParams>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DisplayedPrice'
        /// </summary>
        [Fact]
        public void DisplayedPriceTest()
        {
            // TODO unit test for the property 'DisplayedPrice'
        }

        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }

        /// <summary>
        /// Test the property 'MediaURL'
        /// </summary>
        [Fact]
        public void MediaURLTest()
        {
            // TODO unit test for the property 'MediaURL'
        }

        /// <summary>
        /// Test the property 'AdditionalInfoURL'
        /// </summary>
        [Fact]
        public void AdditionalInfoURLTest()
        {
            // TODO unit test for the property 'AdditionalInfoURL'
        }
    }
}
