/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTEmailSubscriberCreateParamsWalletUI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTEmailSubscriberCreateParamsWalletUITests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTEmailSubscriberCreateParamsWalletUI
        //private WTEmailSubscriberCreateParamsWalletUI instance;

        public WTEmailSubscriberCreateParamsWalletUITests()
        {
            // TODO uncomment below to create an instance of WTEmailSubscriberCreateParamsWalletUI
            //instance = new WTEmailSubscriberCreateParamsWalletUI();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTEmailSubscriberCreateParamsWalletUI
        /// </summary>
        [Fact]
        public void WTEmailSubscriberCreateParamsWalletUIInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTEmailSubscriberCreateParamsWalletUI
            //Assert.IsType<WTEmailSubscriberCreateParamsWalletUI>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }

        /// <summary>
        /// Test the property 'MerchantID'
        /// </summary>
        [Fact]
        public void MerchantIDTest()
        {
            // TODO unit test for the property 'MerchantID'
        }
    }
}
