/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTEmployee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTEmployeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTEmployee
        //private WTEmployee instance;

        public WTEmployeeTests()
        {
            // TODO uncomment below to create an instance of WTEmployee
            //instance = new WTEmployee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTEmployee
        /// </summary>
        [Fact]
        public void WTEmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTEmployee
            //Assert.IsType<WTEmployee>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'IsPublicRepresentative'
        /// </summary>
        [Fact]
        public void IsPublicRepresentativeTest()
        {
            // TODO unit test for the property 'IsPublicRepresentative'
        }

        /// <summary>
        /// Test the property 'WalletSequenceNumber'
        /// </summary>
        [Fact]
        public void WalletSequenceNumberTest()
        {
            // TODO unit test for the property 'WalletSequenceNumber'
        }

        /// <summary>
        /// Test the property 'EmployeeID'
        /// </summary>
        [Fact]
        public void EmployeeIDTest()
        {
            // TODO unit test for the property 'EmployeeID'
        }

        /// <summary>
        /// Test the property 'JobTitle'
        /// </summary>
        [Fact]
        public void JobTitleTest()
        {
            // TODO unit test for the property 'JobTitle'
        }

        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }

        /// <summary>
        /// Test the property 'ScheduleStartDay'
        /// </summary>
        [Fact]
        public void ScheduleStartDayTest()
        {
            // TODO unit test for the property 'ScheduleStartDay'
        }

        /// <summary>
        /// Test the property 'ScheduleStartHour'
        /// </summary>
        [Fact]
        public void ScheduleStartHourTest()
        {
            // TODO unit test for the property 'ScheduleStartHour'
        }

        /// <summary>
        /// Test the property 'ScheduleStartMinute'
        /// </summary>
        [Fact]
        public void ScheduleStartMinuteTest()
        {
            // TODO unit test for the property 'ScheduleStartMinute'
        }

        /// <summary>
        /// Test the property 'ScheduleStartMeridiem'
        /// </summary>
        [Fact]
        public void ScheduleStartMeridiemTest()
        {
            // TODO unit test for the property 'ScheduleStartMeridiem'
        }

        /// <summary>
        /// Test the property 'ScheduleEndDay'
        /// </summary>
        [Fact]
        public void ScheduleEndDayTest()
        {
            // TODO unit test for the property 'ScheduleEndDay'
        }

        /// <summary>
        /// Test the property 'ScheduleEndHour'
        /// </summary>
        [Fact]
        public void ScheduleEndHourTest()
        {
            // TODO unit test for the property 'ScheduleEndHour'
        }

        /// <summary>
        /// Test the property 'ScheduleEndMinute'
        /// </summary>
        [Fact]
        public void ScheduleEndMinuteTest()
        {
            // TODO unit test for the property 'ScheduleEndMinute'
        }

        /// <summary>
        /// Test the property 'ScheduleEndMeridiem'
        /// </summary>
        [Fact]
        public void ScheduleEndMeridiemTest()
        {
            // TODO unit test for the property 'ScheduleEndMeridiem'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }

        /// <summary>
        /// Test the property 'ProfilePictureURL'
        /// </summary>
        [Fact]
        public void ProfilePictureURLTest()
        {
            // TODO unit test for the property 'ProfilePictureURL'
        }

        /// <summary>
        /// Test the property 'MerchantID'
        /// </summary>
        [Fact]
        public void MerchantIDTest()
        {
            // TODO unit test for the property 'MerchantID'
        }

        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Fact]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }

        /// <summary>
        /// Test the property 'FailedLoginAttempts'
        /// </summary>
        [Fact]
        public void FailedLoginAttemptsTest()
        {
            // TODO unit test for the property 'FailedLoginAttempts'
        }

        /// <summary>
        /// Test the property 'LastLoginDate'
        /// </summary>
        [Fact]
        public void LastLoginDateTest()
        {
            // TODO unit test for the property 'LastLoginDate'
        }

        /// <summary>
        /// Test the property 'Cfuvid'
        /// </summary>
        [Fact]
        public void CfuvidTest()
        {
            // TODO unit test for the property 'Cfuvid'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

        /// <summary>
        /// Test the property 'IsEmailNotificationDisabled'
        /// </summary>
        [Fact]
        public void IsEmailNotificationDisabledTest()
        {
            // TODO unit test for the property 'IsEmailNotificationDisabled'
        }
    }
}
