/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTImageGridCreateParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTImageGridCreateParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTImageGridCreateParams
        //private WTImageGridCreateParams instance;

        public WTImageGridCreateParamsTests()
        {
            // TODO uncomment below to create an instance of WTImageGridCreateParams
            //instance = new WTImageGridCreateParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTImageGridCreateParams
        /// </summary>
        [Fact]
        public void WTImageGridCreateParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTImageGridCreateParams
            //Assert.IsType<WTImageGridCreateParams>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'MediaURL'
        /// </summary>
        [Fact]
        public void MediaURLTest()
        {
            // TODO unit test for the property 'MediaURL'
        }

        /// <summary>
        /// Test the property 'SequenceNumber'
        /// </summary>
        [Fact]
        public void SequenceNumberTest()
        {
            // TODO unit test for the property 'SequenceNumber'
        }

        /// <summary>
        /// Test the property 'IsPinned'
        /// </summary>
        [Fact]
        public void IsPinnedTest()
        {
            // TODO unit test for the property 'IsPinned'
        }
    }
}
