/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTQuickLinkUpdateParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTQuickLinkUpdateParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTQuickLinkUpdateParams
        //private WTQuickLinkUpdateParams instance;

        public WTQuickLinkUpdateParamsTests()
        {
            // TODO uncomment below to create an instance of WTQuickLinkUpdateParams
            //instance = new WTQuickLinkUpdateParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTQuickLinkUpdateParams
        /// </summary>
        [Fact]
        public void WTQuickLinkUpdateParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTQuickLinkUpdateParams
            //Assert.IsType<WTQuickLinkUpdateParams>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }

        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }

        /// <summary>
        /// Test the property 'LinkBookSectionID'
        /// </summary>
        [Fact]
        public void LinkBookSectionIDTest()
        {
            // TODO unit test for the property 'LinkBookSectionID'
        }
    }
}
