/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTSettingsSetPassword
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTSettingsSetPasswordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTSettingsSetPassword
        //private WTSettingsSetPassword instance;

        public WTSettingsSetPasswordTests()
        {
            // TODO uncomment below to create an instance of WTSettingsSetPassword
            //instance = new WTSettingsSetPassword();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTSettingsSetPassword
        /// </summary>
        [Fact]
        public void WTSettingsSetPasswordInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTSettingsSetPassword
            //Assert.IsType<WTSettingsSetPassword>(instance);
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
