/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.38.0**, built 2026-08-21T03:57:20.504Z
 *
 * The version of the OpenAPI document: 2.38.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTShareActivityReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTShareActivityReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTShareActivityReport
        //private WTShareActivityReport instance;

        public WTShareActivityReportTests()
        {
            // TODO uncomment below to create an instance of WTShareActivityReport
            //instance = new WTShareActivityReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTShareActivityReport
        /// </summary>
        [Fact]
        public void WTShareActivityReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTShareActivityReport
            //Assert.IsType<WTShareActivityReport>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantID'
        /// </summary>
        [Fact]
        public void MerchantIDTest()
        {
            // TODO unit test for the property 'MerchantID'
        }

        /// <summary>
        /// Test the property 'WindowDays'
        /// </summary>
        [Fact]
        public void WindowDaysTest()
        {
            // TODO unit test for the property 'WindowDays'
        }

        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }

        /// <summary>
        /// Test the property 'Totals'
        /// </summary>
        [Fact]
        public void TotalsTest()
        {
            // TODO unit test for the property 'Totals'
        }
    }
}
