/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTSMSOptInListSourceCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTSMSOptInListSourceCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTSMSOptInListSourceCreate
        //private WTSMSOptInListSourceCreate instance;

        public WTSMSOptInListSourceCreateTests()
        {
            // TODO uncomment below to create an instance of WTSMSOptInListSourceCreate
            //instance = new WTSMSOptInListSourceCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTSMSOptInListSourceCreate
        /// </summary>
        [Fact]
        public void WTSMSOptInListSourceCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTSMSOptInListSourceCreate
            //Assert.IsType<WTSMSOptInListSourceCreate>(instance);
        }

        /// <summary>
        /// Test the property 'ListID'
        /// </summary>
        [Fact]
        public void ListIDTest()
        {
            // TODO unit test for the property 'ListID'
        }

        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Fact]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }
    }
}
