/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WalletInc.Model;
using WalletInc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WalletInc.Test.Model
{
    /// <summary>
    ///  Class for testing WTTicketUpdateParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WTTicketUpdateParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WTTicketUpdateParams
        //private WTTicketUpdateParams instance;

        public WTTicketUpdateParamsTests()
        {
            // TODO uncomment below to create an instance of WTTicketUpdateParams
            //instance = new WTTicketUpdateParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WTTicketUpdateParams
        /// </summary>
        [Fact]
        public void WTTicketUpdateParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WTTicketUpdateParams
            //Assert.IsType<WTTicketUpdateParams>(instance);
        }

        /// <summary>
        /// Test the property 'RecipientPhoneNumber'
        /// </summary>
        [Fact]
        public void RecipientPhoneNumberTest()
        {
            // TODO unit test for the property 'RecipientPhoneNumber'
        }

        /// <summary>
        /// Test the property 'RecipientEmailAddress'
        /// </summary>
        [Fact]
        public void RecipientEmailAddressTest()
        {
            // TODO unit test for the property 'RecipientEmailAddress'
        }

        /// <summary>
        /// Test the property 'RecipientMemberID'
        /// </summary>
        [Fact]
        public void RecipientMemberIDTest()
        {
            // TODO unit test for the property 'RecipientMemberID'
        }

        /// <summary>
        /// Test the property 'IsComp'
        /// </summary>
        [Fact]
        public void IsCompTest()
        {
            // TODO unit test for the property 'IsComp'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
