/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.38.0**, built 2026-08-21T03:57:20.504Z
 *
 * The version of the OpenAPI document: 2.38.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// A2PSoleProprietorSubmission
    /// </summary>
    [DataContract(Name = "A2PSoleProprietorSubmission")]
    public partial class A2PSoleProprietorSubmission : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets BusinessType
        /// </summary>
        [DataMember(Name = "businessType", IsRequired = true, EmitDefaultValue = true)]
        public BusinessTypeSoleProprietorship BusinessType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="A2PSoleProprietorSubmission" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected A2PSoleProprietorSubmission() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="A2PSoleProprietorSubmission" /> class.
        /// </summary>
        /// <param name="firstName">firstName (required).</param>
        /// <param name="lastName">lastName (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="billingConsent">billingConsent.</param>
        /// <param name="businessName">businessName (required).</param>
        /// <param name="businessType">businessType (required).</param>
        /// <param name="address1">address1 (required).</param>
        /// <param name="address2">address2.</param>
        /// <param name="city">city (required).</param>
        /// <param name="state">state (required).</param>
        /// <param name="postalCode">postalCode (required).</param>
        /// <param name="country">country (required).</param>
        /// <param name="phoneNumber">phoneNumber (required).</param>
        /// <param name="isTwilioTermsRead">isTwilioTermsRead (required).</param>
        /// <param name="isWalletSmsTermsRead">isWalletSmsTermsRead (required).</param>
        /// <param name="isPricingUnderstood">isPricingUnderstood (required).</param>
        /// <param name="isPrivacyAndTosPresent">isPrivacyAndTosPresent (required).</param>
        /// <param name="privacyPolicyUrl">privacyPolicyUrl.</param>
        /// <param name="willObtainConsent">willObtainConsent (required).</param>
        /// <param name="willHonorOptOut">willHonorOptOut (required).</param>
        /// <param name="willFollowContentRules">willFollowContentRules (required).</param>
        /// <param name="willComplyLawAndHours">willComplyLawAndHours (required).</param>
        /// <param name="infoIsAccurate">infoIsAccurate (required).</param>
        /// <param name="verificationMobile">verificationMobile (required).</param>
        public A2PSoleProprietorSubmission(string firstName = default, string lastName = default, string email = default, A2PBillingConsent billingConsent = default, string businessName = default, BusinessTypeSoleProprietorship businessType = default, string address1 = default, string address2 = default, string city = default, string state = default, string postalCode = default, string country = default, string phoneNumber = default, bool isTwilioTermsRead = default, bool isWalletSmsTermsRead = default, bool isPricingUnderstood = default, bool isPrivacyAndTosPresent = default, string privacyPolicyUrl = default, bool willObtainConsent = default, bool willHonorOptOut = default, bool willFollowContentRules = default, bool willComplyLawAndHours = default, bool infoIsAccurate = default, string verificationMobile = default)
        {
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.FirstName = firstName;
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.LastName = lastName;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.Email = email;
            // to ensure "businessName" is required (not null)
            if (businessName == null)
            {
                throw new ArgumentNullException("businessName is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.BusinessName = businessName;
            this.BusinessType = businessType;
            // to ensure "address1" is required (not null)
            if (address1 == null)
            {
                throw new ArgumentNullException("address1 is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.Address1 = address1;
            // to ensure "city" is required (not null)
            if (city == null)
            {
                throw new ArgumentNullException("city is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.City = city;
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new ArgumentNullException("state is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.State = state;
            // to ensure "postalCode" is required (not null)
            if (postalCode == null)
            {
                throw new ArgumentNullException("postalCode is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.PostalCode = postalCode;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.Country = country;
            // to ensure "phoneNumber" is required (not null)
            if (phoneNumber == null)
            {
                throw new ArgumentNullException("phoneNumber is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.PhoneNumber = phoneNumber;
            this.IsTwilioTermsRead = isTwilioTermsRead;
            this.IsWalletSmsTermsRead = isWalletSmsTermsRead;
            this.IsPricingUnderstood = isPricingUnderstood;
            this.IsPrivacyAndTosPresent = isPrivacyAndTosPresent;
            this.WillObtainConsent = willObtainConsent;
            this.WillHonorOptOut = willHonorOptOut;
            this.WillFollowContentRules = willFollowContentRules;
            this.WillComplyLawAndHours = willComplyLawAndHours;
            this.InfoIsAccurate = infoIsAccurate;
            // to ensure "verificationMobile" is required (not null)
            if (verificationMobile == null)
            {
                throw new ArgumentNullException("verificationMobile is a required property for A2PSoleProprietorSubmission and cannot be null");
            }
            this.VerificationMobile = verificationMobile;
            this.BillingConsent = billingConsent;
            this.Address2 = address2;
            this.PrivacyPolicyUrl = privacyPolicyUrl;
        }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        /*
        <example>John</example>
        */
        [DataMember(Name = "firstName", IsRequired = true, EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        /*
        <example>Doe</example>
        */
        [DataMember(Name = "lastName", IsRequired = true, EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets BillingConsent
        /// </summary>
        [DataMember(Name = "billingConsent", EmitDefaultValue = false)]
        public A2PBillingConsent BillingConsent { get; set; }

        /// <summary>
        /// Gets or Sets BusinessName
        /// </summary>
        /*
        <example>Acme Corp</example>
        */
        [DataMember(Name = "businessName", IsRequired = true, EmitDefaultValue = true)]
        public string BusinessName { get; set; }

        /// <summary>
        /// Gets or Sets Address1
        /// </summary>
        /*
        <example>21 Jump Street</example>
        */
        [DataMember(Name = "address1", IsRequired = true, EmitDefaultValue = true)]
        public string Address1 { get; set; }

        /// <summary>
        /// Gets or Sets Address2
        /// </summary>
        /*
        <example>https://google.com</example>
        */
        [DataMember(Name = "address2", EmitDefaultValue = false)]
        public string Address2 { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        /*
        <example>Los Angeles</example>
        */
        [DataMember(Name = "city", IsRequired = true, EmitDefaultValue = true)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        /*
        <example>California</example>
        */
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        /*
        <example>90210</example>
        */
        [DataMember(Name = "postalCode", IsRequired = true, EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        /*
        <example>US</example>
        */
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        /*
        <example>+1 800 123 4567</example>
        */
        [DataMember(Name = "phoneNumber", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsTwilioTermsRead
        /// </summary>
        [DataMember(Name = "isTwilioTermsRead", IsRequired = true, EmitDefaultValue = true)]
        public bool IsTwilioTermsRead { get; set; }

        /// <summary>
        /// Gets or Sets IsWalletSmsTermsRead
        /// </summary>
        [DataMember(Name = "isWalletSmsTermsRead", IsRequired = true, EmitDefaultValue = true)]
        public bool IsWalletSmsTermsRead { get; set; }

        /// <summary>
        /// Gets or Sets IsPricingUnderstood
        /// </summary>
        [DataMember(Name = "isPricingUnderstood", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPricingUnderstood { get; set; }

        /// <summary>
        /// Gets or Sets IsPrivacyAndTosPresent
        /// </summary>
        [DataMember(Name = "isPrivacyAndTosPresent", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPrivacyAndTosPresent { get; set; }

        /// <summary>
        /// Gets or Sets PrivacyPolicyUrl
        /// </summary>
        [DataMember(Name = "privacyPolicyUrl", EmitDefaultValue = false)]
        public string PrivacyPolicyUrl { get; set; }

        /// <summary>
        /// Gets or Sets WillObtainConsent
        /// </summary>
        [DataMember(Name = "willObtainConsent", IsRequired = true, EmitDefaultValue = true)]
        public bool WillObtainConsent { get; set; }

        /// <summary>
        /// Gets or Sets WillHonorOptOut
        /// </summary>
        [DataMember(Name = "willHonorOptOut", IsRequired = true, EmitDefaultValue = true)]
        public bool WillHonorOptOut { get; set; }

        /// <summary>
        /// Gets or Sets WillFollowContentRules
        /// </summary>
        [DataMember(Name = "willFollowContentRules", IsRequired = true, EmitDefaultValue = true)]
        public bool WillFollowContentRules { get; set; }

        /// <summary>
        /// Gets or Sets WillComplyLawAndHours
        /// </summary>
        [DataMember(Name = "willComplyLawAndHours", IsRequired = true, EmitDefaultValue = true)]
        public bool WillComplyLawAndHours { get; set; }

        /// <summary>
        /// Gets or Sets InfoIsAccurate
        /// </summary>
        [DataMember(Name = "infoIsAccurate", IsRequired = true, EmitDefaultValue = true)]
        public bool InfoIsAccurate { get; set; }

        /// <summary>
        /// Gets or Sets VerificationMobile
        /// </summary>
        [DataMember(Name = "verificationMobile", IsRequired = true, EmitDefaultValue = true)]
        public string VerificationMobile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class A2PSoleProprietorSubmission {\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  BillingConsent: ").Append(BillingConsent).Append("\n");
            sb.Append("  BusinessName: ").Append(BusinessName).Append("\n");
            sb.Append("  BusinessType: ").Append(BusinessType).Append("\n");
            sb.Append("  Address1: ").Append(Address1).Append("\n");
            sb.Append("  Address2: ").Append(Address2).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  IsTwilioTermsRead: ").Append(IsTwilioTermsRead).Append("\n");
            sb.Append("  IsWalletSmsTermsRead: ").Append(IsWalletSmsTermsRead).Append("\n");
            sb.Append("  IsPricingUnderstood: ").Append(IsPricingUnderstood).Append("\n");
            sb.Append("  IsPrivacyAndTosPresent: ").Append(IsPrivacyAndTosPresent).Append("\n");
            sb.Append("  PrivacyPolicyUrl: ").Append(PrivacyPolicyUrl).Append("\n");
            sb.Append("  WillObtainConsent: ").Append(WillObtainConsent).Append("\n");
            sb.Append("  WillHonorOptOut: ").Append(WillHonorOptOut).Append("\n");
            sb.Append("  WillFollowContentRules: ").Append(WillFollowContentRules).Append("\n");
            sb.Append("  WillComplyLawAndHours: ").Append(WillComplyLawAndHours).Append("\n");
            sb.Append("  InfoIsAccurate: ").Append(InfoIsAccurate).Append("\n");
            sb.Append("  VerificationMobile: ").Append(VerificationMobile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FirstName (string) minLength
            if (this.FirstName != null && this.FirstName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for FirstName, length must be greater than 1.", new [] { "FirstName" });
            }

            // LastName (string) minLength
            if (this.LastName != null && this.LastName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for LastName, length must be greater than 1.", new [] { "LastName" });
            }

            // Email (string) minLength
            if (this.Email != null && this.Email.Length < 6)
            {
                yield return new ValidationResult("Invalid value for Email, length must be greater than 6.", new [] { "Email" });
            }

            // BusinessName (string) minLength
            if (this.BusinessName != null && this.BusinessName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for BusinessName, length must be greater than 1.", new [] { "BusinessName" });
            }

            // Address1 (string) minLength
            if (this.Address1 != null && this.Address1.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Address1, length must be greater than 1.", new [] { "Address1" });
            }

            // Address2 (string) minLength
            if (this.Address2 != null && this.Address2.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Address2, length must be greater than 0.", new [] { "Address2" });
            }

            // City (string) minLength
            if (this.City != null && this.City.Length < 3)
            {
                yield return new ValidationResult("Invalid value for City, length must be greater than 3.", new [] { "City" });
            }

            // State (string) minLength
            if (this.State != null && this.State.Length < 1)
            {
                yield return new ValidationResult("Invalid value for State, length must be greater than 1.", new [] { "State" });
            }

            // PostalCode (string) minLength
            if (this.PostalCode != null && this.PostalCode.Length < 4)
            {
                yield return new ValidationResult("Invalid value for PostalCode, length must be greater than 4.", new [] { "PostalCode" });
            }

            // Country (string) minLength
            if (this.Country != null && this.Country.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Country, length must be greater than 2.", new [] { "Country" });
            }

            // PhoneNumber (string) minLength
            if (this.PhoneNumber != null && this.PhoneNumber.Length < 7)
            {
                yield return new ValidationResult("Invalid value for PhoneNumber, length must be greater than 7.", new [] { "PhoneNumber" });
            }

            yield break;
        }
    }

}
