/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-05T23:10:43.591Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// AdvertisementCreditScan
    /// </summary>
    [DataContract(Name = "AdvertisementCreditScan")]
    public partial class AdvertisementCreditScan : IValidatableObject
    {
        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TransactionTypeEnum
        {
            /// <summary>
            /// Enum Redemption for value: redemption
            /// </summary>
            [EnumMember(Value = "redemption")]
            Redemption = 1,

            /// <summary>
            /// Enum Refund for value: refund
            /// </summary>
            [EnumMember(Value = "refund")]
            Refund = 2,

            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 3
        }


        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        /*
        <example>redemption</example>
        */
        [DataMember(Name = "transactionType", IsRequired = true, EmitDefaultValue = true)]
        public TransactionTypeEnum TransactionType { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdvertisementCreditScan" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AdvertisementCreditScan() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdvertisementCreditScan" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="transactionType">The type of the transaction - only redemption at the moment (required).</param>
        /// <param name="registerID">registerID (required).</param>
        /// <param name="redeemedSource">redeemedSource (required).</param>
        /// <param name="redeemedTransactionID">redeemedTransactionID (required).</param>
        /// <param name="redeemedAmount">redeemedAmount (required).</param>
        /// <param name="isRedeemed">isRedeemed (required).</param>
        /// <param name="refundedTransactionID">refundedTransactionID (required).</param>
        /// <param name="refundedAmount">refundedAmount (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="authorizedAgainstCheckNumber">authorizedAgainstCheckNumber (required).</param>
        /// <param name="authorizedAmount">authorizedAmount (required).</param>
        /// <param name="merchantID">merchantID (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="advertisementCreditID">advertisementCreditID (required).</param>
        /// <param name="redeemedAmountDecimal">redeemedAmountDecimal (required).</param>
        /// <param name="redeemedAmountString">redeemedAmountString (required).</param>
        /// <param name="authorizedAmountDecimal">authorizedAmountDecimal (required).</param>
        /// <param name="authorizedAmountString">authorizedAmountString (required).</param>
        /// <param name="dateTimeRedeemed">dateTimeRedeemed (required).</param>
        /// <param name="dateTimeRefunded">dateTimeRefunded (required).</param>
        public AdvertisementCreditScan(StaticVoucherId id = default, TransactionTypeEnum transactionType = default, PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID registerID = default, string redeemedSource = default, string redeemedTransactionID = default, int redeemedAmount = default, bool isRedeemed = default, string refundedTransactionID = default, int refundedAmount = default, Status status = default, string authorizedAgainstCheckNumber = default, int authorizedAmount = default, string merchantID = default, DateTime createdAt = default, DateTime updatedAt = default, bool isActive = default, string advertisementCreditID = default, string redeemedAmountDecimal = default, string redeemedAmountString = default, string authorizedAmountDecimal = default, string authorizedAmountString = default, DateTime dateTimeRedeemed = default, DateTime dateTimeRefunded = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.Id = id;
            this.TransactionType = transactionType;
            // to ensure "registerID" is required (not null)
            if (registerID == null)
            {
                throw new ArgumentNullException("registerID is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RegisterID = registerID;
            // to ensure "redeemedSource" is required (not null)
            if (redeemedSource == null)
            {
                throw new ArgumentNullException("redeemedSource is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RedeemedSource = redeemedSource;
            // to ensure "redeemedTransactionID" is required (not null)
            if (redeemedTransactionID == null)
            {
                throw new ArgumentNullException("redeemedTransactionID is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RedeemedTransactionID = redeemedTransactionID;
            this.RedeemedAmount = redeemedAmount;
            this.IsRedeemed = isRedeemed;
            // to ensure "refundedTransactionID" is required (not null)
            if (refundedTransactionID == null)
            {
                throw new ArgumentNullException("refundedTransactionID is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RefundedTransactionID = refundedTransactionID;
            this.RefundedAmount = refundedAmount;
            this.Status = status;
            // to ensure "authorizedAgainstCheckNumber" is required (not null)
            if (authorizedAgainstCheckNumber == null)
            {
                throw new ArgumentNullException("authorizedAgainstCheckNumber is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.AuthorizedAgainstCheckNumber = authorizedAgainstCheckNumber;
            this.AuthorizedAmount = authorizedAmount;
            // to ensure "merchantID" is required (not null)
            if (merchantID == null)
            {
                throw new ArgumentNullException("merchantID is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.MerchantID = merchantID;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.IsActive = isActive;
            // to ensure "advertisementCreditID" is required (not null)
            if (advertisementCreditID == null)
            {
                throw new ArgumentNullException("advertisementCreditID is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.AdvertisementCreditID = advertisementCreditID;
            // to ensure "redeemedAmountDecimal" is required (not null)
            if (redeemedAmountDecimal == null)
            {
                throw new ArgumentNullException("redeemedAmountDecimal is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RedeemedAmountDecimal = redeemedAmountDecimal;
            // to ensure "redeemedAmountString" is required (not null)
            if (redeemedAmountString == null)
            {
                throw new ArgumentNullException("redeemedAmountString is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.RedeemedAmountString = redeemedAmountString;
            // to ensure "authorizedAmountDecimal" is required (not null)
            if (authorizedAmountDecimal == null)
            {
                throw new ArgumentNullException("authorizedAmountDecimal is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.AuthorizedAmountDecimal = authorizedAmountDecimal;
            // to ensure "authorizedAmountString" is required (not null)
            if (authorizedAmountString == null)
            {
                throw new ArgumentNullException("authorizedAmountString is a required property for AdvertisementCreditScan and cannot be null");
            }
            this.AuthorizedAmountString = authorizedAmountString;
            this.DateTimeRedeemed = dateTimeRedeemed;
            this.DateTimeRefunded = dateTimeRefunded;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public StaticVoucherId Id { get; set; }

        /// <summary>
        /// Gets or Sets RegisterID
        /// </summary>
        [DataMember(Name = "registerID", IsRequired = true, EmitDefaultValue = true)]
        public PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID RegisterID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedSource
        /// </summary>
        /*
        <example>AN-47</example>
        */
        [DataMember(Name = "redeemedSource", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedSource { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "redeemedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmount
        /// </summary>
        /*
        <example>540</example>
        */
        [DataMember(Name = "redeemedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RedeemedAmount { get; set; }

        /// <summary>
        /// Gets or Sets IsRedeemed
        /// </summary>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isRedeemed", IsRequired = true, EmitDefaultValue = true)]
        public bool IsRedeemed { get; set; }

        /// <summary>
        /// Gets or Sets RefundedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "refundedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RefundedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RefundedAmount
        /// </summary>
        /*
        <example>540</example>
        */
        [DataMember(Name = "refundedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RefundedAmount { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAgainstCheckNumber
        /// </summary>
        /*
        <example>82jSUWKFLjgaj827</example>
        */
        [DataMember(Name = "authorizedAgainstCheckNumber", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAgainstCheckNumber { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmount
        /// </summary>
        /*
        <example>520</example>
        */
        [DataMember(Name = "authorizedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int AuthorizedAmount { get; set; }

        /// <summary>
        /// Gets or Sets MerchantID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "merchantID", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantID { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets AdvertisementCreditID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "advertisementCreditID", IsRequired = true, EmitDefaultValue = true)]
        public string AdvertisementCreditID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountDecimal
        /// </summary>
        /*
        <example>5.00</example>
        */
        [DataMember(Name = "redeemedAmount_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountDecimal { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountString
        /// </summary>
        /*
        <example>$5.00</example>
        */
        [DataMember(Name = "redeemedAmount_string", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountString { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmountDecimal
        /// </summary>
        /*
        <example>5.00</example>
        */
        [DataMember(Name = "authorizedAmount_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAmountDecimal { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmountString
        /// </summary>
        /*
        <example>$5.00</example>
        */
        [DataMember(Name = "authorizedAmount_string", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAmountString { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeRedeemed
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "dateTimeRedeemed", IsRequired = true, EmitDefaultValue = true)]
        public DateTime DateTimeRedeemed { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeRefunded
        /// </summary>
        /*
        <example>2016-06-22 20:10:25-07</example>
        */
        [DataMember(Name = "dateTimeRefunded", IsRequired = true, EmitDefaultValue = true)]
        public DateTime DateTimeRefunded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdvertisementCreditScan {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  RegisterID: ").Append(RegisterID).Append("\n");
            sb.Append("  RedeemedSource: ").Append(RedeemedSource).Append("\n");
            sb.Append("  RedeemedTransactionID: ").Append(RedeemedTransactionID).Append("\n");
            sb.Append("  RedeemedAmount: ").Append(RedeemedAmount).Append("\n");
            sb.Append("  IsRedeemed: ").Append(IsRedeemed).Append("\n");
            sb.Append("  RefundedTransactionID: ").Append(RefundedTransactionID).Append("\n");
            sb.Append("  RefundedAmount: ").Append(RefundedAmount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AuthorizedAgainstCheckNumber: ").Append(AuthorizedAgainstCheckNumber).Append("\n");
            sb.Append("  AuthorizedAmount: ").Append(AuthorizedAmount).Append("\n");
            sb.Append("  MerchantID: ").Append(MerchantID).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  AdvertisementCreditID: ").Append(AdvertisementCreditID).Append("\n");
            sb.Append("  RedeemedAmountDecimal: ").Append(RedeemedAmountDecimal).Append("\n");
            sb.Append("  RedeemedAmountString: ").Append(RedeemedAmountString).Append("\n");
            sb.Append("  AuthorizedAmountDecimal: ").Append(AuthorizedAmountDecimal).Append("\n");
            sb.Append("  AuthorizedAmountString: ").Append(AuthorizedAmountString).Append("\n");
            sb.Append("  DateTimeRedeemed: ").Append(DateTimeRedeemed).Append("\n");
            sb.Append("  DateTimeRefunded: ").Append(DateTimeRefunded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RedeemedAmount (int) minimum
            if (this.RedeemedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RedeemedAmount, must be a value greater than or equal to 0.", new [] { "RedeemedAmount" });
            }

            // RefundedAmount (int) minimum
            if (this.RefundedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundedAmount, must be a value greater than or equal to 0.", new [] { "RefundedAmount" });
            }

            // AuthorizedAmount (int) minimum
            if (this.AuthorizedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for AuthorizedAmount, must be a value greater than or equal to 0.", new [] { "AuthorizedAmount" });
            }

            // MerchantID (string) maxLength
            if (this.MerchantID != null && this.MerchantID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be less than 10.", new [] { "MerchantID" });
            }

            // MerchantID (string) minLength
            if (this.MerchantID != null && this.MerchantID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be greater than 10.", new [] { "MerchantID" });
            }

            if (this.MerchantID != null) {
                // MerchantID (string) pattern
                Regex regexMerchantID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexMerchantID.Match(this.MerchantID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MerchantID, must match a pattern of " + regexMerchantID, new [] { "MerchantID" });
                }
            }

            // AdvertisementCreditID (string) maxLength
            if (this.AdvertisementCreditID != null && this.AdvertisementCreditID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for AdvertisementCreditID, length must be less than 10.", new [] { "AdvertisementCreditID" });
            }

            // AdvertisementCreditID (string) minLength
            if (this.AdvertisementCreditID != null && this.AdvertisementCreditID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for AdvertisementCreditID, length must be greater than 10.", new [] { "AdvertisementCreditID" });
            }

            if (this.AdvertisementCreditID != null) {
                // AdvertisementCreditID (string) pattern
                Regex regexAdvertisementCreditID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexAdvertisementCreditID.Match(this.AdvertisementCreditID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AdvertisementCreditID, must match a pattern of " + regexAdvertisementCreditID, new [] { "AdvertisementCreditID" });
                }
            }

            yield break;
        }
    }

}
