/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T03:43:13.036Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// Defines BusinessClassification
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BusinessClassification
    {
        /// <summary>
        /// Enum Public for value: public
        /// </summary>
        [EnumMember(Value = "public")]
        Public = 1,

        /// <summary>
        /// Enum Private for value: private
        /// </summary>
        [EnumMember(Value = "private")]
        Private = 2,

        /// <summary>
        /// Enum NonProfit for value: non-profit
        /// </summary>
        [EnumMember(Value = "non-profit")]
        NonProfit = 3,

        /// <summary>
        /// Enum Government for value: government
        /// </summary>
        [EnumMember(Value = "government")]
        Government = 4
    }

}
