/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-27T15:17:15.438Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// Defines BusinessType.SoleProprietorship
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BusinessTypeSoleProprietorship
    {
        /// <summary>
        /// Enum SoleProprietorship for value: Sole Proprietorship
        /// </summary>
        [EnumMember(Value = "Sole Proprietorship")]
        SoleProprietorship = 1
    }

}
