/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-07-30T18:47:43.121Z
 *
 * The version of the OpenAPI document: 2.20.2
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// Defines BusinessClassification.NonProfit
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BusinessClassificationNonProfit
    {
        /// <summary>
        /// Enum NonProfit for value: non-profit
        /// </summary>
        [EnumMember(Value = "non-profit")]
        NonProfit = 1
    }

}
