/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-08T14:47:43.573Z
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// CountClaimedComps200Response
    /// </summary>
    [DataContract(Name = "countClaimedComps_200_response")]
    public partial class CountClaimedComps200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CountClaimedComps200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CountClaimedComps200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CountClaimedComps200Response" /> class.
        /// </summary>
        /// <param name="seats">seats (required).</param>
        /// <param name="count">count (required).</param>
        public CountClaimedComps200Response(double seats = default, double count = default)
        {
            this.Seats = seats;
            this.Count = count;
        }

        /// <summary>
        /// Gets or Sets Seats
        /// </summary>
        [DataMember(Name = "seats", IsRequired = true, EmitDefaultValue = true)]
        public double Seats { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public double Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CountClaimedComps200Response {\n");
            sb.Append("  Seats: ").Append(Seats).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
