/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.44.0**, built 2026-09-01T14:02:40.244Z
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// CSPViolationSummaryRow
    /// </summary>
    [DataContract(Name = "CSPViolationSummaryRow")]
    public partial class CSPViolationSummaryRow : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CSPViolationSummaryRow" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CSPViolationSummaryRow()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CSPViolationSummaryRow" /> class.
        /// </summary>
        /// <param name="violatedDirective">violatedDirective (required).</param>
        /// <param name="blockedHost">The scheme+host of the blocked URI, or the raw value for schemeless blocks (inline / eval / data:). (required).</param>
        /// <param name="disposition">\&quot;enforce\&quot; (actually blocked) vs \&quot;report\&quot; (report-only twin). (required).</param>
        /// <param name="count">count (required).</param>
        /// <param name="sampleDocumentURI">sampleDocumentURI (required).</param>
        /// <param name="firstSeen">firstSeen.</param>
        /// <param name="lastSeen">lastSeen.</param>
        public CSPViolationSummaryRow(string violatedDirective = default, string blockedHost = default, string disposition = default, int count = default, string sampleDocumentURI = default, DateTime firstSeen = default, DateTime lastSeen = default)
        {
            // to ensure "violatedDirective" is required (not null)
            if (violatedDirective == null)
            {
                throw new ArgumentNullException("violatedDirective is a required property for CSPViolationSummaryRow and cannot be null");
            }
            this.ViolatedDirective = violatedDirective;
            // to ensure "blockedHost" is required (not null)
            if (blockedHost == null)
            {
                throw new ArgumentNullException("blockedHost is a required property for CSPViolationSummaryRow and cannot be null");
            }
            this.BlockedHost = blockedHost;
            // to ensure "disposition" is required (not null)
            if (disposition == null)
            {
                throw new ArgumentNullException("disposition is a required property for CSPViolationSummaryRow and cannot be null");
            }
            this.Disposition = disposition;
            this.Count = count;
            // to ensure "sampleDocumentURI" is required (not null)
            if (sampleDocumentURI == null)
            {
                throw new ArgumentNullException("sampleDocumentURI is a required property for CSPViolationSummaryRow and cannot be null");
            }
            this.SampleDocumentURI = sampleDocumentURI;
            this.FirstSeen = firstSeen;
            this.LastSeen = lastSeen;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets ViolatedDirective
        /// </summary>
        [DataMember(Name = "violatedDirective", IsRequired = true, EmitDefaultValue = true)]
        public string ViolatedDirective { get; set; }

        /// <summary>
        /// The scheme+host of the blocked URI, or the raw value for schemeless blocks (inline / eval / data:).
        /// </summary>
        /// <value>The scheme+host of the blocked URI, or the raw value for schemeless blocks (inline / eval / data:).</value>
        [DataMember(Name = "blockedHost", IsRequired = true, EmitDefaultValue = true)]
        public string BlockedHost { get; set; }

        /// <summary>
        /// \&quot;enforce\&quot; (actually blocked) vs \&quot;report\&quot; (report-only twin).
        /// </summary>
        /// <value>\&quot;enforce\&quot; (actually blocked) vs \&quot;report\&quot; (report-only twin).</value>
        [DataMember(Name = "disposition", IsRequired = true, EmitDefaultValue = true)]
        public string Disposition { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets SampleDocumentURI
        /// </summary>
        [DataMember(Name = "sampleDocumentURI", IsRequired = true, EmitDefaultValue = true)]
        public string SampleDocumentURI { get; set; }

        /// <summary>
        /// Gets or Sets FirstSeen
        /// </summary>
        [DataMember(Name = "firstSeen", EmitDefaultValue = false)]
        public DateTime FirstSeen { get; set; }

        /// <summary>
        /// Gets or Sets LastSeen
        /// </summary>
        [DataMember(Name = "lastSeen", EmitDefaultValue = false)]
        public DateTime LastSeen { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CSPViolationSummaryRow {\n");
            sb.Append("  ViolatedDirective: ").Append(ViolatedDirective).Append("\n");
            sb.Append("  BlockedHost: ").Append(BlockedHost).Append("\n");
            sb.Append("  Disposition: ").Append(Disposition).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  SampleDocumentURI: ").Append(SampleDocumentURI).Append("\n");
            sb.Append("  FirstSeen: ").Append(FirstSeen).Append("\n");
            sb.Append("  LastSeen: ").Append(LastSeen).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
