/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-15T18:14:39.381Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// FetchAllLedgerTransactions200Response
    /// </summary>
    [DataContract(Name = "fetchAllLedgerTransactions_200_response")]
    public partial class FetchAllLedgerTransactions200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchAllLedgerTransactions200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FetchAllLedgerTransactions200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchAllLedgerTransactions200Response" /> class.
        /// </summary>
        /// <param name="entries">entries (required).</param>
        /// <param name="pageCount">pageCount (required).</param>
        /// <param name="totalRecords">totalRecords (required).</param>
        public FetchAllLedgerTransactions200Response(List<LedgerEntry> entries = default, double pageCount = default, double totalRecords = default)
        {
            // to ensure "entries" is required (not null)
            if (entries == null)
            {
                throw new ArgumentNullException("entries is a required property for FetchAllLedgerTransactions200Response and cannot be null");
            }
            this.Entries = entries;
            this.PageCount = pageCount;
            this.TotalRecords = totalRecords;
        }

        /// <summary>
        /// Gets or Sets Entries
        /// </summary>
        [DataMember(Name = "entries", IsRequired = true, EmitDefaultValue = true)]
        public List<LedgerEntry> Entries { get; set; }

        /// <summary>
        /// Gets or Sets PageCount
        /// </summary>
        [DataMember(Name = "pageCount", IsRequired = true, EmitDefaultValue = true)]
        public double PageCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalRecords
        /// </summary>
        [DataMember(Name = "totalRecords", IsRequired = true, EmitDefaultValue = true)]
        public double TotalRecords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FetchAllLedgerTransactions200Response {\n");
            sb.Append("  Entries: ").Append(Entries).Append("\n");
            sb.Append("  PageCount: ").Append(PageCount).Append("\n");
            sb.Append("  TotalRecords: ").Append(TotalRecords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
