/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.44.0**, built 2026-09-01T13:15:47.228Z
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// FetchIndustry200ResponseAnyOf1
    /// </summary>
    [DataContract(Name = "fetchIndustry_200_response_anyOf_1")]
    public partial class FetchIndustry200ResponseAnyOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchIndustry200ResponseAnyOf1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FetchIndustry200ResponseAnyOf1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchIndustry200ResponseAnyOf1" /> class.
        /// </summary>
        /// <param name="isIndustrySelected">isIndustrySelected (required).</param>
        public FetchIndustry200ResponseAnyOf1(bool isIndustrySelected = default)
        {
            this.IsIndustrySelected = isIndustrySelected;
        }

        /// <summary>
        /// Gets or Sets IsIndustrySelected
        /// </summary>
        [DataMember(Name = "isIndustrySelected", IsRequired = true, EmitDefaultValue = true)]
        public bool IsIndustrySelected { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FetchIndustry200ResponseAnyOf1 {\n");
            sb.Append("  IsIndustrySelected: ").Append(IsIndustrySelected).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
