/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T22:38:05.866Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// ImportedList
    /// </summary>
    [DataContract(Name = "ImportedList")]
    public partial class ImportedList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportedList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImportedList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportedList" /> class.
        /// </summary>
        /// <param name="employeeID">employeeID (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="listName">listName (required).</param>
        /// <param name="phoneNumberID">phoneNumberID (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="merchantID">merchantID (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public ImportedList(string employeeID = default, bool isActive = default, string listName = default, string phoneNumberID = default, StaticVoucherId id = default, Object merchantID = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            // to ensure "employeeID" is required (not null)
            if (employeeID == null)
            {
                throw new ArgumentNullException("employeeID is a required property for ImportedList and cannot be null");
            }
            this.EmployeeID = employeeID;
            this.IsActive = isActive;
            // to ensure "listName" is required (not null)
            if (listName == null)
            {
                throw new ArgumentNullException("listName is a required property for ImportedList and cannot be null");
            }
            this.ListName = listName;
            // to ensure "phoneNumberID" is required (not null)
            if (phoneNumberID == null)
            {
                throw new ArgumentNullException("phoneNumberID is a required property for ImportedList and cannot be null");
            }
            this.PhoneNumberID = phoneNumberID;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ImportedList and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantID" is required (not null)
            if (merchantID == null)
            {
                throw new ArgumentNullException("merchantID is a required property for ImportedList and cannot be null");
            }
            this.MerchantID = merchantID;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets EmployeeID
        /// </summary>
        [DataMember(Name = "employeeID", IsRequired = true, EmitDefaultValue = true)]
        public string EmployeeID { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets ListName
        /// </summary>
        /*
        <example>Christmas Offers</example>
        */
        [DataMember(Name = "listName", IsRequired = true, EmitDefaultValue = true)]
        public string ListName { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumberID
        /// </summary>
        [DataMember(Name = "phoneNumberID", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumberID { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public StaticVoucherId Id { get; set; }

        /// <summary>
        /// Gets or Sets MerchantID
        /// </summary>
        /*
        <example>736dhakidk</example>
        */
        [DataMember(Name = "merchantID", IsRequired = true, EmitDefaultValue = true)]
        public Object MerchantID { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportedList {\n");
            sb.Append("  EmployeeID: ").Append(EmployeeID).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ListName: ").Append(ListName).Append("\n");
            sb.Append("  PhoneNumberID: ").Append(PhoneNumberID).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantID: ").Append(MerchantID).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EmployeeID (string) maxLength
            if (this.EmployeeID != null && this.EmployeeID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be less than 10.", new [] { "EmployeeID" });
            }

            // EmployeeID (string) minLength
            if (this.EmployeeID != null && this.EmployeeID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be greater than 10.", new [] { "EmployeeID" });
            }

            if (this.EmployeeID != null) {
                // EmployeeID (string) pattern
                Regex regexEmployeeID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexEmployeeID.Match(this.EmployeeID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EmployeeID, must match a pattern of " + regexEmployeeID, new [] { "EmployeeID" });
                }
            }

            // PhoneNumberID (string) maxLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be less than 10.", new [] { "PhoneNumberID" });
            }

            // PhoneNumberID (string) minLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be greater than 10.", new [] { "PhoneNumberID" });
            }

            if (this.PhoneNumberID != null) {
                // PhoneNumberID (string) pattern
                Regex regexPhoneNumberID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexPhoneNumberID.Match(this.PhoneNumberID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumberID, must match a pattern of " + regexPhoneNumberID, new [] { "PhoneNumberID" });
                }
            }

            yield break;
        }
    }

}
