/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.8.0**, built 2026-07-15T17:36:04.148Z
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// MerchantCreditSearch
    /// </summary>
    [DataContract(Name = "MerchantCreditSearch")]
    public partial class MerchantCreditSearch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantCreditSearch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MerchantCreditSearch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantCreditSearch" /> class.
        /// </summary>
        /// <param name="isArchiveIncluded">Denotes if archived records should be included in the response payload.</param>
        /// <param name="pageSize">Denotes the number of records per page.</param>
        /// <param name="pageNum">Denotes the page number.</param>
        /// <param name="key">The search key to be used (required).</param>
        public MerchantCreditSearch(bool isArchiveIncluded = default, int pageSize = default, int pageNum = default, string key = default)
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for MerchantCreditSearch and cannot be null");
            }
            this.Key = key;
            this.IsArchiveIncluded = isArchiveIncluded;
            this.PageSize = pageSize;
            this.PageNum = pageNum;
        }

        /// <summary>
        /// Denotes if archived records should be included in the response payload
        /// </summary>
        /// <value>Denotes if archived records should be included in the response payload</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isArchiveIncluded", EmitDefaultValue = true)]
        public bool IsArchiveIncluded { get; set; }

        /// <summary>
        /// Denotes the number of records per page
        /// </summary>
        /// <value>Denotes the number of records per page</value>
        /*
        <example>20</example>
        */
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public int PageSize { get; set; }

        /// <summary>
        /// Denotes the page number
        /// </summary>
        /// <value>Denotes the page number</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "pageNum", EmitDefaultValue = false)]
        public int PageNum { get; set; }

        /// <summary>
        /// The search key to be used
        /// </summary>
        /// <value>The search key to be used</value>
        /*
        <example>MEM001</example>
        */
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MerchantCreditSearch {\n");
            sb.Append("  IsArchiveIncluded: ").Append(IsArchiveIncluded).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  PageNum: ").Append(PageNum).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
