/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.2.1**, built 2026-07-04T20:30:37.614Z
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// From T, pick a set of properties whose keys are in the union K
    /// </summary>
    [DataContract(Name = "Pick_SSOptInListUpdateParams.Exclude_keyofSSOptInListUpdateParams.id__")]
    public partial class PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId" /> class.
        /// </summary>
        /// <param name="employeeID">employeeID (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="listName">listName (required).</param>
        /// <param name="phoneNumberID">phoneNumberID (required).</param>
        /// <param name="estimatedMessagesPerMonth">estimatedMessagesPerMonth (required).</param>
        /// <param name="optInKeyword">optInKeyword (required).</param>
        /// <param name="optOutKeyword">optOutKeyword (required).</param>
        /// <param name="optInConfirmedResponse">optInConfirmedResponse (required).</param>
        /// <param name="optOutConfirmedResponse">optOutConfirmedResponse (required).</param>
        /// <param name="optInConfirmedCustomerReceives">optInConfirmedCustomerReceives (required).</param>
        /// <param name="optOutConfirmedCustomerReceives">optOutConfirmedCustomerReceives (required).</param>
        /// <param name="optInConfirmedMediaURLs">optInConfirmedMediaURLs (required).</param>
        /// <param name="optOutConfirmedMediaURLs">optOutConfirmedMediaURLs (required).</param>
        /// <param name="isOver21Required">isOver21Required (required).</param>
        public PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId(string employeeID = default, bool isActive = default, string listName = default, string phoneNumberID = default, int estimatedMessagesPerMonth = default, string optInKeyword = default, string optOutKeyword = default, string optInConfirmedResponse = default, string optOutConfirmedResponse = default, string optInConfirmedCustomerReceives = default, string optOutConfirmedCustomerReceives = default, List<string> optInConfirmedMediaURLs = default, List<string> optOutConfirmedMediaURLs = default, bool isOver21Required = default)
        {
            // to ensure "employeeID" is required (not null)
            if (employeeID == null)
            {
                throw new ArgumentNullException("employeeID is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.EmployeeID = employeeID;
            this.IsActive = isActive;
            // to ensure "listName" is required (not null)
            if (listName == null)
            {
                throw new ArgumentNullException("listName is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.ListName = listName;
            // to ensure "phoneNumberID" is required (not null)
            if (phoneNumberID == null)
            {
                throw new ArgumentNullException("phoneNumberID is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.PhoneNumberID = phoneNumberID;
            this.EstimatedMessagesPerMonth = estimatedMessagesPerMonth;
            // to ensure "optInKeyword" is required (not null)
            if (optInKeyword == null)
            {
                throw new ArgumentNullException("optInKeyword is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptInKeyword = optInKeyword;
            // to ensure "optOutKeyword" is required (not null)
            if (optOutKeyword == null)
            {
                throw new ArgumentNullException("optOutKeyword is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptOutKeyword = optOutKeyword;
            // to ensure "optInConfirmedResponse" is required (not null)
            if (optInConfirmedResponse == null)
            {
                throw new ArgumentNullException("optInConfirmedResponse is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptInConfirmedResponse = optInConfirmedResponse;
            // to ensure "optOutConfirmedResponse" is required (not null)
            if (optOutConfirmedResponse == null)
            {
                throw new ArgumentNullException("optOutConfirmedResponse is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptOutConfirmedResponse = optOutConfirmedResponse;
            // to ensure "optInConfirmedCustomerReceives" is required (not null)
            if (optInConfirmedCustomerReceives == null)
            {
                throw new ArgumentNullException("optInConfirmedCustomerReceives is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptInConfirmedCustomerReceives = optInConfirmedCustomerReceives;
            // to ensure "optOutConfirmedCustomerReceives" is required (not null)
            if (optOutConfirmedCustomerReceives == null)
            {
                throw new ArgumentNullException("optOutConfirmedCustomerReceives is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptOutConfirmedCustomerReceives = optOutConfirmedCustomerReceives;
            // to ensure "optInConfirmedMediaURLs" is required (not null)
            if (optInConfirmedMediaURLs == null)
            {
                throw new ArgumentNullException("optInConfirmedMediaURLs is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptInConfirmedMediaURLs = optInConfirmedMediaURLs;
            // to ensure "optOutConfirmedMediaURLs" is required (not null)
            if (optOutConfirmedMediaURLs == null)
            {
                throw new ArgumentNullException("optOutConfirmedMediaURLs is a required property for PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId and cannot be null");
            }
            this.OptOutConfirmedMediaURLs = optOutConfirmedMediaURLs;
            this.IsOver21Required = isOver21Required;
        }

        /// <summary>
        /// Gets or Sets EmployeeID
        /// </summary>
        [DataMember(Name = "employeeID", IsRequired = true, EmitDefaultValue = true)]
        public string EmployeeID { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets ListName
        /// </summary>
        /*
        <example>Christmas Offers</example>
        */
        [DataMember(Name = "listName", IsRequired = true, EmitDefaultValue = true)]
        public string ListName { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumberID
        /// </summary>
        [DataMember(Name = "phoneNumberID", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumberID { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedMessagesPerMonth
        /// </summary>
        /*
        <example>2500</example>
        */
        [DataMember(Name = "estimatedMessagesPerMonth", IsRequired = true, EmitDefaultValue = true)]
        public int EstimatedMessagesPerMonth { get; set; }

        /// <summary>
        /// Gets or Sets OptInKeyword
        /// </summary>
        /*
        <example>SUBS</example>
        */
        [DataMember(Name = "optInKeyword", IsRequired = true, EmitDefaultValue = true)]
        public string OptInKeyword { get; set; }

        /// <summary>
        /// Gets or Sets OptOutKeyword
        /// </summary>
        /*
        <example>UNSUB</example>
        */
        [DataMember(Name = "optOutKeyword", IsRequired = true, EmitDefaultValue = true)]
        public string OptOutKeyword { get; set; }

        /// <summary>
        /// Gets or Sets OptInConfirmedResponse
        /// </summary>
        /*
        <example>Welcome to the list</example>
        */
        [DataMember(Name = "optInConfirmedResponse", IsRequired = true, EmitDefaultValue = true)]
        public string OptInConfirmedResponse { get; set; }

        /// <summary>
        /// Gets or Sets OptOutConfirmedResponse
        /// </summary>
        /*
        <example>Sorry to see you go</example>
        */
        [DataMember(Name = "optOutConfirmedResponse", IsRequired = true, EmitDefaultValue = true)]
        public string OptOutConfirmedResponse { get; set; }

        /// <summary>
        /// Gets or Sets OptInConfirmedCustomerReceives
        /// </summary>
        /*
        <example>Welcome to the list</example>
        */
        [DataMember(Name = "optInConfirmedCustomerReceives", IsRequired = true, EmitDefaultValue = true)]
        public string OptInConfirmedCustomerReceives { get; set; }

        /// <summary>
        /// Gets or Sets OptOutConfirmedCustomerReceives
        /// </summary>
        /*
        <example>Sorry to see you go</example>
        */
        [DataMember(Name = "optOutConfirmedCustomerReceives", IsRequired = true, EmitDefaultValue = true)]
        public string OptOutConfirmedCustomerReceives { get; set; }

        /// <summary>
        /// Gets or Sets OptInConfirmedMediaURLs
        /// </summary>
        [DataMember(Name = "optInConfirmedMediaURLs", IsRequired = true, EmitDefaultValue = true)]
        public List<string> OptInConfirmedMediaURLs { get; set; }

        /// <summary>
        /// Gets or Sets OptOutConfirmedMediaURLs
        /// </summary>
        [DataMember(Name = "optOutConfirmedMediaURLs", IsRequired = true, EmitDefaultValue = true)]
        public List<string> OptOutConfirmedMediaURLs { get; set; }

        /// <summary>
        /// Gets or Sets IsOver21Required
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isOver21Required", IsRequired = true, EmitDefaultValue = true)]
        public bool IsOver21Required { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PickSSOptInListUpdateParamsExcludeKeyofSSOptInListUpdateParamsId {\n");
            sb.Append("  EmployeeID: ").Append(EmployeeID).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ListName: ").Append(ListName).Append("\n");
            sb.Append("  PhoneNumberID: ").Append(PhoneNumberID).Append("\n");
            sb.Append("  EstimatedMessagesPerMonth: ").Append(EstimatedMessagesPerMonth).Append("\n");
            sb.Append("  OptInKeyword: ").Append(OptInKeyword).Append("\n");
            sb.Append("  OptOutKeyword: ").Append(OptOutKeyword).Append("\n");
            sb.Append("  OptInConfirmedResponse: ").Append(OptInConfirmedResponse).Append("\n");
            sb.Append("  OptOutConfirmedResponse: ").Append(OptOutConfirmedResponse).Append("\n");
            sb.Append("  OptInConfirmedCustomerReceives: ").Append(OptInConfirmedCustomerReceives).Append("\n");
            sb.Append("  OptOutConfirmedCustomerReceives: ").Append(OptOutConfirmedCustomerReceives).Append("\n");
            sb.Append("  OptInConfirmedMediaURLs: ").Append(OptInConfirmedMediaURLs).Append("\n");
            sb.Append("  OptOutConfirmedMediaURLs: ").Append(OptOutConfirmedMediaURLs).Append("\n");
            sb.Append("  IsOver21Required: ").Append(IsOver21Required).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EmployeeID (string) maxLength
            if (this.EmployeeID != null && this.EmployeeID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be less than 10.", new [] { "EmployeeID" });
            }

            // EmployeeID (string) minLength
            if (this.EmployeeID != null && this.EmployeeID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be greater than 10.", new [] { "EmployeeID" });
            }

            if (this.EmployeeID != null) {
                // EmployeeID (string) pattern
                Regex regexEmployeeID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexEmployeeID.Match(this.EmployeeID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EmployeeID, must match a pattern of " + regexEmployeeID, new [] { "EmployeeID" });
                }
            }

            // ListName (string) minLength
            if (this.ListName != null && this.ListName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ListName, length must be greater than 1.", new [] { "ListName" });
            }

            // PhoneNumberID (string) maxLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be less than 10.", new [] { "PhoneNumberID" });
            }

            // PhoneNumberID (string) minLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be greater than 10.", new [] { "PhoneNumberID" });
            }

            if (this.PhoneNumberID != null) {
                // PhoneNumberID (string) pattern
                Regex regexPhoneNumberID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexPhoneNumberID.Match(this.PhoneNumberID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumberID, must match a pattern of " + regexPhoneNumberID, new [] { "PhoneNumberID" });
                }
            }

            // EstimatedMessagesPerMonth (int) minimum
            if (this.EstimatedMessagesPerMonth < (int)0)
            {
                yield return new ValidationResult("Invalid value for EstimatedMessagesPerMonth, must be a value greater than or equal to 0.", new [] { "EstimatedMessagesPerMonth" });
            }

            // OptInKeyword (string) maxLength
            if (this.OptInKeyword != null && this.OptInKeyword.Length > 30)
            {
                yield return new ValidationResult("Invalid value for OptInKeyword, length must be less than 30.", new [] { "OptInKeyword" });
            }

            // OptInKeyword (string) minLength
            if (this.OptInKeyword != null && this.OptInKeyword.Length < 4)
            {
                yield return new ValidationResult("Invalid value for OptInKeyword, length must be greater than 4.", new [] { "OptInKeyword" });
            }

            // OptOutKeyword (string) maxLength
            if (this.OptOutKeyword != null && this.OptOutKeyword.Length > 34)
            {
                yield return new ValidationResult("Invalid value for OptOutKeyword, length must be less than 34.", new [] { "OptOutKeyword" });
            }

            // OptOutKeyword (string) minLength
            if (this.OptOutKeyword != null && this.OptOutKeyword.Length < 4)
            {
                yield return new ValidationResult("Invalid value for OptOutKeyword, length must be greater than 4.", new [] { "OptOutKeyword" });
            }

            yield break;
        }
    }

}
