/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-24T12:43:25.662Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// SimpleSMSBroadcast
    /// </summary>
    [DataContract(Name = "SimpleSMSBroadcast")]
    public partial class SimpleSMSBroadcast : IValidatableObject
    {
        /// <summary>
        /// Defines BroadcastStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BroadcastStatusEnum
        {
            /// <summary>
            /// Enum Created for value: created
            /// </summary>
            [EnumMember(Value = "created")]
            Created = 1,

            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            [EnumMember(Value = "queued")]
            Queued = 2,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            [EnumMember(Value = "running")]
            Running = 3,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 4,

            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            Cancelled = 5
        }


        /// <summary>
        /// Gets or Sets BroadcastStatus
        /// </summary>
        /*
        <example>created</example>
        */
        [DataMember(Name = "broadcastStatus", IsRequired = true, EmitDefaultValue = true)]
        public BroadcastStatusEnum BroadcastStatus { get; set; }
        /// <summary>
        /// Defines ListType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ListTypeEnum
        {
            /// <summary>
            /// Enum OptInKeywordList for value: opt-in-keyword-list
            /// </summary>
            [EnumMember(Value = "opt-in-keyword-list")]
            OptInKeywordList = 1,

            /// <summary>
            /// Enum ImportedList for value: imported-list
            /// </summary>
            [EnumMember(Value = "imported-list")]
            ImportedList = 2,

            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 3
        }


        /// <summary>
        /// Gets or Sets ListType
        /// </summary>
        /*
        <example>opt-in-keyword-list</example>
        */
        [DataMember(Name = "listType", IsRequired = true, EmitDefaultValue = true)]
        public ListTypeEnum ListType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleSMSBroadcast" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SimpleSMSBroadcast() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleSMSBroadcast" /> class.
        /// </summary>
        /// <param name="phoneNumberID">phoneNumberID (required).</param>
        /// <param name="paymentObjectPrefix">paymentObjectPrefix (required).</param>
        /// <param name="paymentObjectID">paymentObjectID (required).</param>
        /// <param name="messageTemplate">messageTemplate (required).</param>
        /// <param name="mediaURLs">mediaURLs (required).</param>
        /// <param name="employeeID">employeeID (required).</param>
        /// <param name="broadcastScheduledAt">broadcastScheduledAt (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="merchantID">merchantID (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="broadcastStatus">broadcastStatus (required).</param>
        /// <param name="broadcastQueuedAt">broadcastQueuedAt (required).</param>
        /// <param name="broadcastStartedAt">broadcastStartedAt (required).</param>
        /// <param name="broadcastCompletedAt">broadcastCompletedAt (required).</param>
        /// <param name="listType">listType (required).</param>
        /// <param name="listID">listID (required).</param>
        /// <param name="optInList">optInList.</param>
        /// <param name="importedList">importedList.</param>
        public SimpleSMSBroadcast(string phoneNumberID = default, PickWTPaymentObjectBroadcastExcludeKeyofWTPaymentObjectBroadcastListTypeOrListIDPaymentObjectPrefix paymentObjectPrefix = default, string paymentObjectID = default, string messageTemplate = default, List<string> mediaURLs = default, string employeeID = default, DateTime broadcastScheduledAt = default, StaticVoucherId id = default, Object merchantID = default, DateTime createdAt = default, DateTime updatedAt = default, bool isActive = default, BroadcastStatusEnum broadcastStatus = default, DateTime broadcastQueuedAt = default, DateTime broadcastStartedAt = default, DateTime broadcastCompletedAt = default, ListTypeEnum listType = default, string listID = default, WTOptInList optInList = default, WTImportedList importedList = default)
        {
            // to ensure "phoneNumberID" is required (not null)
            if (phoneNumberID == null)
            {
                throw new ArgumentNullException("phoneNumberID is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.PhoneNumberID = phoneNumberID;
            // to ensure "paymentObjectPrefix" is required (not null)
            if (paymentObjectPrefix == null)
            {
                throw new ArgumentNullException("paymentObjectPrefix is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.PaymentObjectPrefix = paymentObjectPrefix;
            // to ensure "paymentObjectID" is required (not null)
            if (paymentObjectID == null)
            {
                throw new ArgumentNullException("paymentObjectID is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.PaymentObjectID = paymentObjectID;
            // to ensure "messageTemplate" is required (not null)
            if (messageTemplate == null)
            {
                throw new ArgumentNullException("messageTemplate is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.MessageTemplate = messageTemplate;
            // to ensure "mediaURLs" is required (not null)
            if (mediaURLs == null)
            {
                throw new ArgumentNullException("mediaURLs is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.MediaURLs = mediaURLs;
            // to ensure "employeeID" is required (not null)
            if (employeeID == null)
            {
                throw new ArgumentNullException("employeeID is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.EmployeeID = employeeID;
            this.BroadcastScheduledAt = broadcastScheduledAt;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantID" is required (not null)
            if (merchantID == null)
            {
                throw new ArgumentNullException("merchantID is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.MerchantID = merchantID;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.IsActive = isActive;
            this.BroadcastStatus = broadcastStatus;
            this.BroadcastQueuedAt = broadcastQueuedAt;
            this.BroadcastStartedAt = broadcastStartedAt;
            this.BroadcastCompletedAt = broadcastCompletedAt;
            this.ListType = listType;
            // to ensure "listID" is required (not null)
            if (listID == null)
            {
                throw new ArgumentNullException("listID is a required property for SimpleSMSBroadcast and cannot be null");
            }
            this.ListID = listID;
            this.OptInList = optInList;
            this.ImportedList = importedList;
        }

        /// <summary>
        /// Gets or Sets PhoneNumberID
        /// </summary>
        [DataMember(Name = "phoneNumberID", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumberID { get; set; }

        /// <summary>
        /// Gets or Sets PaymentObjectPrefix
        /// </summary>
        [DataMember(Name = "paymentObjectPrefix", IsRequired = true, EmitDefaultValue = true)]
        public PickWTPaymentObjectBroadcastExcludeKeyofWTPaymentObjectBroadcastListTypeOrListIDPaymentObjectPrefix PaymentObjectPrefix { get; set; }

        /// <summary>
        /// Gets or Sets PaymentObjectID
        /// </summary>
        [DataMember(Name = "paymentObjectID", IsRequired = true, EmitDefaultValue = true)]
        public string PaymentObjectID { get; set; }

        /// <summary>
        /// Gets or Sets MessageTemplate
        /// </summary>
        /*
        <example>Hey [member], this is a new static voucher for you of $[value].</example>
        */
        [DataMember(Name = "messageTemplate", IsRequired = true, EmitDefaultValue = true)]
        public string MessageTemplate { get; set; }

        /// <summary>
        /// Gets or Sets MediaURLs
        /// </summary>
        [DataMember(Name = "mediaURLs", IsRequired = true, EmitDefaultValue = true)]
        public List<string> MediaURLs { get; set; }

        /// <summary>
        /// Gets or Sets EmployeeID
        /// </summary>
        [DataMember(Name = "employeeID", IsRequired = true, EmitDefaultValue = true)]
        public string EmployeeID { get; set; }

        /// <summary>
        /// Gets or Sets BroadcastScheduledAt
        /// </summary>
        /*
        <example>2021-01-18 19:10:25-07</example>
        */
        [DataMember(Name = "broadcastScheduledAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime BroadcastScheduledAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public StaticVoucherId Id { get; set; }

        /// <summary>
        /// Gets or Sets MerchantID
        /// </summary>
        /*
        <example>736dhakidk</example>
        */
        [DataMember(Name = "merchantID", IsRequired = true, EmitDefaultValue = true)]
        public Object MerchantID { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets BroadcastQueuedAt
        /// </summary>
        /*
        <example>2021-01-18 19:10:26-07</example>
        */
        [DataMember(Name = "broadcastQueuedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime BroadcastQueuedAt { get; set; }

        /// <summary>
        /// Gets or Sets BroadcastStartedAt
        /// </summary>
        /*
        <example>2021-01-18 19:10:26-07</example>
        */
        [DataMember(Name = "broadcastStartedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime BroadcastStartedAt { get; set; }

        /// <summary>
        /// Gets or Sets BroadcastCompletedAt
        /// </summary>
        /*
        <example>2021-01-18 19:11:26-07</example>
        */
        [DataMember(Name = "broadcastCompletedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime BroadcastCompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets ListID
        /// </summary>
        [DataMember(Name = "listID", IsRequired = true, EmitDefaultValue = true)]
        public string ListID { get; set; }

        /// <summary>
        /// Gets or Sets OptInList
        /// </summary>
        [DataMember(Name = "OptInList", EmitDefaultValue = false)]
        public WTOptInList OptInList { get; set; }

        /// <summary>
        /// Gets or Sets ImportedList
        /// </summary>
        [DataMember(Name = "ImportedList", EmitDefaultValue = false)]
        public WTImportedList ImportedList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimpleSMSBroadcast {\n");
            sb.Append("  PhoneNumberID: ").Append(PhoneNumberID).Append("\n");
            sb.Append("  PaymentObjectPrefix: ").Append(PaymentObjectPrefix).Append("\n");
            sb.Append("  PaymentObjectID: ").Append(PaymentObjectID).Append("\n");
            sb.Append("  MessageTemplate: ").Append(MessageTemplate).Append("\n");
            sb.Append("  MediaURLs: ").Append(MediaURLs).Append("\n");
            sb.Append("  EmployeeID: ").Append(EmployeeID).Append("\n");
            sb.Append("  BroadcastScheduledAt: ").Append(BroadcastScheduledAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantID: ").Append(MerchantID).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  BroadcastStatus: ").Append(BroadcastStatus).Append("\n");
            sb.Append("  BroadcastQueuedAt: ").Append(BroadcastQueuedAt).Append("\n");
            sb.Append("  BroadcastStartedAt: ").Append(BroadcastStartedAt).Append("\n");
            sb.Append("  BroadcastCompletedAt: ").Append(BroadcastCompletedAt).Append("\n");
            sb.Append("  ListType: ").Append(ListType).Append("\n");
            sb.Append("  ListID: ").Append(ListID).Append("\n");
            sb.Append("  OptInList: ").Append(OptInList).Append("\n");
            sb.Append("  ImportedList: ").Append(ImportedList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PhoneNumberID (string) maxLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be less than 10.", new [] { "PhoneNumberID" });
            }

            // PhoneNumberID (string) minLength
            if (this.PhoneNumberID != null && this.PhoneNumberID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for PhoneNumberID, length must be greater than 10.", new [] { "PhoneNumberID" });
            }

            if (this.PhoneNumberID != null) {
                // PhoneNumberID (string) pattern
                Regex regexPhoneNumberID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexPhoneNumberID.Match(this.PhoneNumberID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumberID, must match a pattern of " + regexPhoneNumberID, new [] { "PhoneNumberID" });
                }
            }

            // PaymentObjectID (string) maxLength
            if (this.PaymentObjectID != null && this.PaymentObjectID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PaymentObjectID, length must be less than 10.", new [] { "PaymentObjectID" });
            }

            // PaymentObjectID (string) minLength
            if (this.PaymentObjectID != null && this.PaymentObjectID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for PaymentObjectID, length must be greater than 10.", new [] { "PaymentObjectID" });
            }

            if (this.PaymentObjectID != null) {
                // PaymentObjectID (string) pattern
                Regex regexPaymentObjectID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexPaymentObjectID.Match(this.PaymentObjectID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PaymentObjectID, must match a pattern of " + regexPaymentObjectID, new [] { "PaymentObjectID" });
                }
            }

            // EmployeeID (string) maxLength
            if (this.EmployeeID != null && this.EmployeeID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be less than 10.", new [] { "EmployeeID" });
            }

            // EmployeeID (string) minLength
            if (this.EmployeeID != null && this.EmployeeID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for EmployeeID, length must be greater than 10.", new [] { "EmployeeID" });
            }

            if (this.EmployeeID != null) {
                // EmployeeID (string) pattern
                Regex regexEmployeeID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexEmployeeID.Match(this.EmployeeID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EmployeeID, must match a pattern of " + regexEmployeeID, new [] { "EmployeeID" });
                }
            }

            // ListID (string) maxLength
            if (this.ListID != null && this.ListID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for ListID, length must be less than 10.", new [] { "ListID" });
            }

            // ListID (string) minLength
            if (this.ListID != null && this.ListID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for ListID, length must be greater than 10.", new [] { "ListID" });
            }

            if (this.ListID != null) {
                // ListID (string) pattern
                Regex regexListID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexListID.Match(this.ListID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ListID, must match a pattern of " + regexListID, new [] { "ListID" });
                }
            }

            yield break;
        }
    }

}
