/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.6.0**, built 2026-07-12T13:58:10.751Z
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTAuthenticationLoginRequest
    /// </summary>
    [DataContract(Name = "WTAuthenticationLoginRequest")]
    public partial class WTAuthenticationLoginRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WTAuthenticationLoginRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTAuthenticationLoginRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTAuthenticationLoginRequest" /> class.
        /// </summary>
        /// <param name="username">username (required).</param>
        /// <param name="password">password (required).</param>
        public WTAuthenticationLoginRequest(string username = default, string password = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for WTAuthenticationLoginRequest and cannot be null");
            }
            this.Username = username;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for WTAuthenticationLoginRequest and cannot be null");
            }
            this.Password = password;
        }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        /*
        <example>username</example>
        */
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTAuthenticationLoginRequest {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Username, length must be greater than 1.", new [] { "Username" });
            }

            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 1.", new [] { "Password" });
            }

            yield break;
        }
    }

}
