/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.50.0**, built 2026-09-29T14:31:11.531Z
 *
 * The version of the OpenAPI document: 2.50.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTAutoResponderUpdateParams
    /// </summary>
    [DataContract(Name = "WTAutoResponderUpdateParams")]
    public partial class WTAutoResponderUpdateParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WTAutoResponderUpdateParams" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTAutoResponderUpdateParams() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTAutoResponderUpdateParams" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="keyword">keyword.</param>
        /// <param name="responseBody">responseBody.</param>
        /// <param name="mediaURLs">mediaURLs.</param>
        public WTAutoResponderUpdateParams(string id = default, string keyword = default, string responseBody = default, List<string> mediaURLs = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WTAutoResponderUpdateParams and cannot be null");
            }
            this.Id = id;
            this.Keyword = keyword;
            this.ResponseBody = responseBody;
            this.MediaURLs = mediaURLs;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Keyword
        /// </summary>
        /*
        <example>BROCHURE</example>
        */
        [DataMember(Name = "keyword", EmitDefaultValue = false)]
        public string Keyword { get; set; }

        /// <summary>
        /// Gets or Sets ResponseBody
        /// </summary>
        /*
        <example>Here&#39;s our brochure! https://example.com/brochure</example>
        */
        [DataMember(Name = "responseBody", EmitDefaultValue = false)]
        public string ResponseBody { get; set; }

        /// <summary>
        /// Gets or Sets MediaURLs
        /// </summary>
        /*
        <example>[https://example.com/brochure.pdf]</example>
        */
        [DataMember(Name = "mediaURLs", EmitDefaultValue = false)]
        public List<string> MediaURLs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTAutoResponderUpdateParams {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Keyword: ").Append(Keyword).Append("\n");
            sb.Append("  ResponseBody: ").Append(ResponseBody).Append("\n");
            sb.Append("  MediaURLs: ").Append(MediaURLs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) maxLength
            if (this.Id != null && this.Id.Length > 10)
            {
                yield return new ValidationResult("Invalid value for Id, length must be less than 10.", new [] { "Id" });
            }

            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 10)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 10.", new [] { "Id" });
            }

            if (this.Id != null) {
                // Id (string) pattern
                Regex regexId = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexId.Match(this.Id).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, must match a pattern of " + regexId, new [] { "Id" });
                }
            }

            // Keyword (string) maxLength
            if (this.Keyword != null && this.Keyword.Length > 60)
            {
                yield return new ValidationResult("Invalid value for Keyword, length must be less than 60.", new [] { "Keyword" });
            }

            // Keyword (string) minLength
            if (this.Keyword != null && this.Keyword.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Keyword, length must be greater than 1.", new [] { "Keyword" });
            }

            yield break;
        }
    }

}
