/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.49.1**, built 2026-09-24T17:20:19.995Z
 *
 * The version of the OpenAPI document: 2.49.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// One in-force merchant agreement, as a signup page needs it.
    /// </summary>
    [DataContract(Name = "WTCurrentMerchantTermsVersion")]
    public partial class WTCurrentMerchantTermsVersion : IValidatableObject
    {

        /// <summary>
        /// Which agreement: \&quot;tos\&quot; or \&quot;privacy\&quot;.
        /// </summary>
        /// <value>Which agreement: \&quot;tos\&quot; or \&quot;privacy\&quot;.</value>
        [DataMember(Name = "documentType", IsRequired = true, EmitDefaultValue = true)]
        public MerchantTermsDocumentType DocumentType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTCurrentMerchantTermsVersion" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTCurrentMerchantTermsVersion()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTCurrentMerchantTermsVersion" /> class.
        /// </summary>
        /// <param name="documentType">Which agreement: \&quot;tos\&quot; or \&quot;privacy\&quot;. (required).</param>
        /// <param name="versionId">The exact id to send back as &#x60;acceptedTermsVersion&#x60; / &#x60;acceptedPrivacyVersion&#x60; on registration. (required).</param>
        /// <param name="effectiveDate">When this version came into force. (required).</param>
        /// <param name="url">The document the merchant should be shown and link to. (required).</param>
        public WTCurrentMerchantTermsVersion(MerchantTermsDocumentType documentType = default, string versionId = default, string effectiveDate = default, string url = default)
        {
            this.DocumentType = documentType;
            // to ensure "versionId" is required (not null)
            if (versionId == null)
            {
                throw new ArgumentNullException("versionId is a required property for WTCurrentMerchantTermsVersion and cannot be null");
            }
            this.VersionId = versionId;
            // to ensure "effectiveDate" is required (not null)
            if (effectiveDate == null)
            {
                throw new ArgumentNullException("effectiveDate is a required property for WTCurrentMerchantTermsVersion and cannot be null");
            }
            this.EffectiveDate = effectiveDate;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for WTCurrentMerchantTermsVersion and cannot be null");
            }
            this.Url = url;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The exact id to send back as &#x60;acceptedTermsVersion&#x60; / &#x60;acceptedPrivacyVersion&#x60; on registration.
        /// </summary>
        /// <value>The exact id to send back as &#x60;acceptedTermsVersion&#x60; / &#x60;acceptedPrivacyVersion&#x60; on registration.</value>
        [DataMember(Name = "versionId", IsRequired = true, EmitDefaultValue = true)]
        public string VersionId { get; set; }

        /// <summary>
        /// When this version came into force.
        /// </summary>
        /// <value>When this version came into force.</value>
        [DataMember(Name = "effectiveDate", IsRequired = true, EmitDefaultValue = true)]
        public string EffectiveDate { get; set; }

        /// <summary>
        /// The document the merchant should be shown and link to.
        /// </summary>
        /// <value>The document the merchant should be shown and link to.</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTCurrentMerchantTermsVersion {\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  EffectiveDate: ").Append(EffectiveDate).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
