/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.3**, built 2026-07-09T22:41:33.079Z
 *
 * The version of the OpenAPI document: 2.4.3
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTDynamicVoucherRedemption
    /// </summary>
    [DataContract(Name = "WTDynamicVoucherRedemption")]
    public partial class WTDynamicVoucherRedemption : IValidatableObject
    {
        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TransactionTypeEnum
        {
            /// <summary>
            /// Enum Redemption for value: redemption
            /// </summary>
            [EnumMember(Value = "redemption")]
            Redemption = 1,

            /// <summary>
            /// Enum Refund for value: refund
            /// </summary>
            [EnumMember(Value = "refund")]
            Refund = 2
        }


        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        /*
        <example>redemption</example>
        */
        [DataMember(Name = "transactionType", IsRequired = true, EmitDefaultValue = true)]
        public TransactionTypeEnum TransactionType { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public VSDynamicVoucherStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTDynamicVoucherRedemption" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTDynamicVoucherRedemption() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTDynamicVoucherRedemption" /> class.
        /// </summary>
        /// <param name="sessionKey">sessionKey (required).</param>
        /// <param name="redeemedAmount">redeemedAmount (required).</param>
        /// <param name="dynamicVoucherID">dynamicVoucherID (required).</param>
        /// <param name="redeemedSource">redeemedSource (required).</param>
        /// <param name="redeemedTransactionID">redeemedTransactionID (required).</param>
        /// <param name="transactionType">The type of the transaction - only redemption at the moment (required).</param>
        /// <param name="registerID">registerID (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="merchantID">merchantID (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="redeemedAt">redeemedAt.</param>
        /// <param name="refundedAt">refundedAt.</param>
        /// <param name="refundedTransactionID">refundedTransactionID (required).</param>
        /// <param name="refundedAmount">refundedAmount (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="redeemedAmountDecimal">redeemedAmountDecimal (required).</param>
        /// <param name="redeemedAmountString">redeemedAmountString (required).</param>
        /// <param name="discountReceived">discountReceived (required).</param>
        /// <param name="metaValue">metaValue (required).</param>
        /// <param name="parentObjectID">parentObjectID (required).</param>
        public WTDynamicVoucherRedemption(string sessionKey = default, int redeemedAmount = default, string dynamicVoucherID = default, string redeemedSource = default, string redeemedTransactionID = default, TransactionTypeEnum transactionType = default, PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID registerID = default, StaticVoucherId id = default, string merchantID = default, DateTime createdAt = default, DateTime updatedAt = default, bool isActive = default, DateTime redeemedAt = default, DateTime refundedAt = default, string refundedTransactionID = default, int refundedAmount = default, VSDynamicVoucherStatus status = default, string redeemedAmountDecimal = default, string redeemedAmountString = default, string discountReceived = default, string metaValue = default, string parentObjectID = default)
        {
            // to ensure "sessionKey" is required (not null)
            if (sessionKey == null)
            {
                throw new ArgumentNullException("sessionKey is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.SessionKey = sessionKey;
            this.RedeemedAmount = redeemedAmount;
            // to ensure "dynamicVoucherID" is required (not null)
            if (dynamicVoucherID == null)
            {
                throw new ArgumentNullException("dynamicVoucherID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.DynamicVoucherID = dynamicVoucherID;
            // to ensure "redeemedSource" is required (not null)
            if (redeemedSource == null)
            {
                throw new ArgumentNullException("redeemedSource is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RedeemedSource = redeemedSource;
            // to ensure "redeemedTransactionID" is required (not null)
            if (redeemedTransactionID == null)
            {
                throw new ArgumentNullException("redeemedTransactionID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RedeemedTransactionID = redeemedTransactionID;
            this.TransactionType = transactionType;
            // to ensure "registerID" is required (not null)
            if (registerID == null)
            {
                throw new ArgumentNullException("registerID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RegisterID = registerID;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantID" is required (not null)
            if (merchantID == null)
            {
                throw new ArgumentNullException("merchantID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.MerchantID = merchantID;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.IsActive = isActive;
            // to ensure "refundedTransactionID" is required (not null)
            if (refundedTransactionID == null)
            {
                throw new ArgumentNullException("refundedTransactionID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RefundedTransactionID = refundedTransactionID;
            this.RefundedAmount = refundedAmount;
            this.Status = status;
            // to ensure "redeemedAmountDecimal" is required (not null)
            if (redeemedAmountDecimal == null)
            {
                throw new ArgumentNullException("redeemedAmountDecimal is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RedeemedAmountDecimal = redeemedAmountDecimal;
            // to ensure "redeemedAmountString" is required (not null)
            if (redeemedAmountString == null)
            {
                throw new ArgumentNullException("redeemedAmountString is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.RedeemedAmountString = redeemedAmountString;
            // to ensure "discountReceived" is required (not null)
            if (discountReceived == null)
            {
                throw new ArgumentNullException("discountReceived is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.DiscountReceived = discountReceived;
            // to ensure "metaValue" is required (not null)
            if (metaValue == null)
            {
                throw new ArgumentNullException("metaValue is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.MetaValue = metaValue;
            // to ensure "parentObjectID" is required (not null)
            if (parentObjectID == null)
            {
                throw new ArgumentNullException("parentObjectID is a required property for WTDynamicVoucherRedemption and cannot be null");
            }
            this.ParentObjectID = parentObjectID;
            this.RedeemedAt = redeemedAt;
            this.RefundedAt = refundedAt;
        }

        /// <summary>
        /// Gets or Sets SessionKey
        /// </summary>
        /*
        <example>AN-47</example>
        */
        [DataMember(Name = "sessionKey", IsRequired = true, EmitDefaultValue = true)]
        public string SessionKey { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmount
        /// </summary>
        /*
        <example>250</example>
        */
        [DataMember(Name = "redeemedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RedeemedAmount { get; set; }

        /// <summary>
        /// Gets or Sets DynamicVoucherID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "dynamicVoucherID", IsRequired = true, EmitDefaultValue = true)]
        public string DynamicVoucherID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedSource
        /// </summary>
        /*
        <example>AN-47</example>
        */
        [DataMember(Name = "redeemedSource", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedSource { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "redeemedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RegisterID
        /// </summary>
        [DataMember(Name = "registerID", IsRequired = true, EmitDefaultValue = true)]
        public PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID RegisterID { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public StaticVoucherId Id { get; set; }

        /// <summary>
        /// Gets or Sets MerchantID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "merchantID", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantID { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "redeemedAt", EmitDefaultValue = false)]
        public DateTime RedeemedAt { get; set; }

        /// <summary>
        /// Gets or Sets RefundedAt
        /// </summary>
        /*
        <example>2016-06-22 20:10:25-07</example>
        */
        [DataMember(Name = "refundedAt", EmitDefaultValue = false)]
        public DateTime RefundedAt { get; set; }

        /// <summary>
        /// Gets or Sets RefundedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "refundedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RefundedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RefundedAmount
        /// </summary>
        /*
        <example>540</example>
        */
        [DataMember(Name = "refundedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RefundedAmount { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountDecimal
        /// </summary>
        /*
        <example>5.00</example>
        */
        [DataMember(Name = "redeemedAmount_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountDecimal { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountString
        /// </summary>
        /*
        <example>$5.00</example>
        */
        [DataMember(Name = "redeemedAmount_string", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountString { get; set; }

        /// <summary>
        /// Gets or Sets DiscountReceived
        /// </summary>
        [DataMember(Name = "discountReceived", IsRequired = true, EmitDefaultValue = true)]
        public string DiscountReceived { get; set; }

        /// <summary>
        /// Gets or Sets MetaValue
        /// </summary>
        [DataMember(Name = "metaValue", IsRequired = true, EmitDefaultValue = true)]
        public string MetaValue { get; set; }

        /// <summary>
        /// Gets or Sets ParentObjectID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "parentObjectID", IsRequired = true, EmitDefaultValue = true)]
        public string ParentObjectID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTDynamicVoucherRedemption {\n");
            sb.Append("  SessionKey: ").Append(SessionKey).Append("\n");
            sb.Append("  RedeemedAmount: ").Append(RedeemedAmount).Append("\n");
            sb.Append("  DynamicVoucherID: ").Append(DynamicVoucherID).Append("\n");
            sb.Append("  RedeemedSource: ").Append(RedeemedSource).Append("\n");
            sb.Append("  RedeemedTransactionID: ").Append(RedeemedTransactionID).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  RegisterID: ").Append(RegisterID).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantID: ").Append(MerchantID).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  RedeemedAt: ").Append(RedeemedAt).Append("\n");
            sb.Append("  RefundedAt: ").Append(RefundedAt).Append("\n");
            sb.Append("  RefundedTransactionID: ").Append(RefundedTransactionID).Append("\n");
            sb.Append("  RefundedAmount: ").Append(RefundedAmount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RedeemedAmountDecimal: ").Append(RedeemedAmountDecimal).Append("\n");
            sb.Append("  RedeemedAmountString: ").Append(RedeemedAmountString).Append("\n");
            sb.Append("  DiscountReceived: ").Append(DiscountReceived).Append("\n");
            sb.Append("  MetaValue: ").Append(MetaValue).Append("\n");
            sb.Append("  ParentObjectID: ").Append(ParentObjectID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RedeemedAmount (int) minimum
            if (this.RedeemedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RedeemedAmount, must be a value greater than or equal to 0.", new [] { "RedeemedAmount" });
            }

            // DynamicVoucherID (string) maxLength
            if (this.DynamicVoucherID != null && this.DynamicVoucherID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for DynamicVoucherID, length must be less than 10.", new [] { "DynamicVoucherID" });
            }

            // DynamicVoucherID (string) minLength
            if (this.DynamicVoucherID != null && this.DynamicVoucherID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for DynamicVoucherID, length must be greater than 10.", new [] { "DynamicVoucherID" });
            }

            if (this.DynamicVoucherID != null) {
                // DynamicVoucherID (string) pattern
                Regex regexDynamicVoucherID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexDynamicVoucherID.Match(this.DynamicVoucherID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DynamicVoucherID, must match a pattern of " + regexDynamicVoucherID, new [] { "DynamicVoucherID" });
                }
            }

            // MerchantID (string) maxLength
            if (this.MerchantID != null && this.MerchantID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be less than 10.", new [] { "MerchantID" });
            }

            // MerchantID (string) minLength
            if (this.MerchantID != null && this.MerchantID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be greater than 10.", new [] { "MerchantID" });
            }

            if (this.MerchantID != null) {
                // MerchantID (string) pattern
                Regex regexMerchantID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexMerchantID.Match(this.MerchantID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MerchantID, must match a pattern of " + regexMerchantID, new [] { "MerchantID" });
                }
            }

            // RefundedAmount (int) minimum
            if (this.RefundedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundedAmount, must be a value greater than or equal to 0.", new [] { "RefundedAmount" });
            }

            // ParentObjectID (string) maxLength
            if (this.ParentObjectID != null && this.ParentObjectID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for ParentObjectID, length must be less than 10.", new [] { "ParentObjectID" });
            }

            // ParentObjectID (string) minLength
            if (this.ParentObjectID != null && this.ParentObjectID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for ParentObjectID, length must be greater than 10.", new [] { "ParentObjectID" });
            }

            if (this.ParentObjectID != null) {
                // ParentObjectID (string) pattern
                Regex regexParentObjectID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexParentObjectID.Match(this.ParentObjectID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ParentObjectID, must match a pattern of " + regexParentObjectID, new [] { "ParentObjectID" });
                }
            }

            yield break;
        }
    }

}
