/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T15:29:59.131Z
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTInfoGenesisUniquePostingIDs
    /// </summary>
    [DataContract(Name = "WTInfoGenesisUniquePostingIDs")]
    public partial class WTInfoGenesisUniquePostingIDs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WTInfoGenesisUniquePostingIDs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTInfoGenesisUniquePostingIDs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTInfoGenesisUniquePostingIDs" /> class.
        /// </summary>
        /// <param name="uniquePostingIDs">uniquePostingIDs (required).</param>
        public WTInfoGenesisUniquePostingIDs(List<string> uniquePostingIDs = default)
        {
            // to ensure "uniquePostingIDs" is required (not null)
            if (uniquePostingIDs == null)
            {
                throw new ArgumentNullException("uniquePostingIDs is a required property for WTInfoGenesisUniquePostingIDs and cannot be null");
            }
            this.UniquePostingIDs = uniquePostingIDs;
        }

        /// <summary>
        /// Gets or Sets UniquePostingIDs
        /// </summary>
        [DataMember(Name = "uniquePostingIDs", IsRequired = true, EmitDefaultValue = true)]
        public List<string> UniquePostingIDs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTInfoGenesisUniquePostingIDs {\n");
            sb.Append("  UniquePostingIDs: ").Append(UniquePostingIDs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
