/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-16T11:49:20.813Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTLeadFiConsumerProfileAssets
    /// </summary>
    [DataContract(Name = "WTLeadFiConsumerProfile_assets")]
    public partial class WTLeadFiConsumerProfileAssets : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WTLeadFiConsumerProfileAssets" /> class.
        /// </summary>
        /// <param name="retirement">retirement.</param>
        /// <param name="investable">investable.</param>
        public WTLeadFiConsumerProfileAssets(string retirement = default, string investable = default)
        {
            this.Retirement = retirement;
            this.Investable = investable;
        }

        /// <summary>
        /// Gets or Sets Retirement
        /// </summary>
        [DataMember(Name = "retirement", EmitDefaultValue = false)]
        public string Retirement { get; set; }

        /// <summary>
        /// Gets or Sets Investable
        /// </summary>
        [DataMember(Name = "investable", EmitDefaultValue = false)]
        public string Investable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTLeadFiConsumerProfileAssets {\n");
            sb.Append("  Retirement: ").Append(Retirement).Append("\n");
            sb.Append("  Investable: ").Append(Investable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
