/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.49.1**, built 2026-09-24T17:20:19.995Z
 *
 * The version of the OpenAPI document: 2.49.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTPassStyleResponseProviders
    /// </summary>
    [DataContract(Name = "WTPassStyleResponse_providers")]
    public partial class WTPassStyleResponseProviders : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WTPassStyleResponseProviders" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTPassStyleResponseProviders() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTPassStyleResponseProviders" /> class.
        /// </summary>
        /// <param name="apple">apple (required).</param>
        /// <param name="google">google (required).</param>
        public WTPassStyleResponseProviders(WTPassStyleResponseProvidersApple apple = default, WTPassStyleResponseProvidersApple google = default)
        {
            // to ensure "apple" is required (not null)
            if (apple == null)
            {
                throw new ArgumentNullException("apple is a required property for WTPassStyleResponseProviders and cannot be null");
            }
            this.Apple = apple;
            // to ensure "google" is required (not null)
            if (google == null)
            {
                throw new ArgumentNullException("google is a required property for WTPassStyleResponseProviders and cannot be null");
            }
            this.Google = google;
        }

        /// <summary>
        /// Gets or Sets Apple
        /// </summary>
        [DataMember(Name = "apple", IsRequired = true, EmitDefaultValue = true)]
        public WTPassStyleResponseProvidersApple Apple { get; set; }

        /// <summary>
        /// Gets or Sets Google
        /// </summary>
        [DataMember(Name = "google", IsRequired = true, EmitDefaultValue = true)]
        public WTPassStyleResponseProvidersApple Google { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTPassStyleResponseProviders {\n");
            sb.Append("  Apple: ").Append(Apple).Append("\n");
            sb.Append("  Google: ").Append(Google).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
