/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-22T16:32:54.438Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTSegmentAdvisory
    /// </summary>
    [DataContract(Name = "WTSegmentAdvisory")]
    public partial class WTSegmentAdvisory : IValidatableObject
    {
        /// <summary>
        /// Defines Recommend
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RecommendEnum
        {
            /// <summary>
            /// Enum None for value: none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 1,

            /// <summary>
            /// Enum AttachImage for value: attach-image
            /// </summary>
            [EnumMember(Value = "attach-image")]
            AttachImage = 2,

            /// <summary>
            /// Enum CleanText for value: clean-text
            /// </summary>
            [EnumMember(Value = "clean-text")]
            CleanText = 3
        }


        /// <summary>
        /// Gets or Sets Recommend
        /// </summary>
        [DataMember(Name = "recommend", IsRequired = true, EmitDefaultValue = true)]
        public RecommendEnum Recommend { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTSegmentAdvisory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTSegmentAdvisory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTSegmentAdvisory" /> class.
        /// </summary>
        /// <param name="recommend">recommend (required).</param>
        /// <param name="perRecipientSaving">perRecipientSaving (required).</param>
        /// <param name="campaignSaving">campaignSaving (required).</param>
        /// <param name="costNeutral">costNeutral (required).</param>
        public WTSegmentAdvisory(RecommendEnum recommend = default, double perRecipientSaving = default, double campaignSaving = default, bool costNeutral = default)
        {
            this.Recommend = recommend;
            this.PerRecipientSaving = perRecipientSaving;
            this.CampaignSaving = campaignSaving;
            this.CostNeutral = costNeutral;
        }

        /// <summary>
        /// Gets or Sets PerRecipientSaving
        /// </summary>
        /*
        <example>3</example>
        */
        [DataMember(Name = "perRecipientSaving", IsRequired = true, EmitDefaultValue = true)]
        public double PerRecipientSaving { get; set; }

        /// <summary>
        /// Gets or Sets CampaignSaving
        /// </summary>
        /*
        <example>750</example>
        */
        [DataMember(Name = "campaignSaving", IsRequired = true, EmitDefaultValue = true)]
        public double CampaignSaving { get; set; }

        /// <summary>
        /// Gets or Sets CostNeutral
        /// </summary>
        /*
        <example>false</example>
        */
        [DataMember(Name = "costNeutral", IsRequired = true, EmitDefaultValue = true)]
        public bool CostNeutral { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTSegmentAdvisory {\n");
            sb.Append("  Recommend: ").Append(Recommend).Append("\n");
            sb.Append("  PerRecipientSaving: ").Append(PerRecipientSaving).Append("\n");
            sb.Append("  CampaignSaving: ").Append(CampaignSaving).Append("\n");
            sb.Append("  CostNeutral: ").Append(CostNeutral).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
