/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T11:22:18.050Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = WalletInc.Client.FileParameter;
using OpenAPIDateConverter = WalletInc.Client.OpenAPIDateConverter;

namespace WalletInc.Model
{
    /// <summary>
    /// WTStaticVoucher
    /// </summary>
    [DataContract(Name = "WTStaticVoucher")]
    public partial class WTStaticVoucher : IValidatableObject
    {
        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TransactionTypeEnum
        {
            /// <summary>
            /// Enum Redemption for value: redemption
            /// </summary>
            [EnumMember(Value = "redemption")]
            Redemption = 1,

            /// <summary>
            /// Enum Refund for value: refund
            /// </summary>
            [EnumMember(Value = "refund")]
            Refund = 2,

            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 3
        }


        /// <summary>
        /// The type of the transaction - only redemption at the moment
        /// </summary>
        /// <value>The type of the transaction - only redemption at the moment</value>
        /*
        <example>redemption</example>
        */
        [DataMember(Name = "transactionType", IsRequired = true, EmitDefaultValue = true)]
        public TransactionTypeEnum TransactionType { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTStaticVoucher" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WTStaticVoucher() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WTStaticVoucher" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="campaignID">campaignID (required).</param>
        /// <param name="memberID">memberID.</param>
        /// <param name="cellPhoneNumber">cellPhoneNumber.</param>
        /// <param name="offerAmountCents">offerAmountCents (required).</param>
        /// <param name="orderNumber">orderNumber (required).</param>
        /// <param name="transactionType">The type of the transaction - only redemption at the moment (required).</param>
        /// <param name="registerID">registerID (required).</param>
        /// <param name="redeemedSource">redeemedSource (required).</param>
        /// <param name="redeemedTransactionID">redeemedTransactionID (required).</param>
        /// <param name="redeemedAmount">redeemedAmount (required).</param>
        /// <param name="isRedeemed">isRedeemed (required).</param>
        /// <param name="refundedTransactionID">refundedTransactionID (required).</param>
        /// <param name="refundedAmount">refundedAmount (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="customerID">customerID.</param>
        /// <param name="authorizedAgainstCheckNumber">authorizedAgainstCheckNumber (required).</param>
        /// <param name="authorizedAmount">authorizedAmount (required).</param>
        /// <param name="merchantID">merchantID (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="authorizedAmountDecimal">authorizedAmountDecimal (required).</param>
        /// <param name="authorizedAmountString">authorizedAmountString (required).</param>
        /// <param name="offerAmountCentsDecimal">offerAmountCentsDecimal (required).</param>
        /// <param name="offerAmountCentsString">offerAmountCentsString (required).</param>
        /// <param name="redeemedAmountDecimal">redeemedAmountDecimal (required).</param>
        /// <param name="redeemedAmountString">redeemedAmountString (required).</param>
        /// <param name="dateTimeRedeemed">dateTimeRedeemed.</param>
        /// <param name="dateTimeRefunded">dateTimeRefunded.</param>
        /// <param name="dateTimeLastViewed">dateTimeLastViewed.</param>
        /// <param name="reasonInvalid">reasonInvalid.</param>
        public WTStaticVoucher(StaticVoucherId id = default, string campaignID = default, string memberID = default, string cellPhoneNumber = default, int offerAmountCents = default, int orderNumber = default, TransactionTypeEnum transactionType = default, PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID registerID = default, string redeemedSource = default, string redeemedTransactionID = default, int redeemedAmount = default, bool isRedeemed = default, string refundedTransactionID = default, int refundedAmount = default, Status status = default, string customerID = default, string authorizedAgainstCheckNumber = default, int authorizedAmount = default, string merchantID = default, DateTime createdAt = default, DateTime updatedAt = default, bool isActive = default, string authorizedAmountDecimal = default, string authorizedAmountString = default, string offerAmountCentsDecimal = default, string offerAmountCentsString = default, string redeemedAmountDecimal = default, string redeemedAmountString = default, DateTime dateTimeRedeemed = default, DateTime dateTimeRefunded = default, DateTime dateTimeLastViewed = default, string reasonInvalid = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WTStaticVoucher and cannot be null");
            }
            this.Id = id;
            // to ensure "campaignID" is required (not null)
            if (campaignID == null)
            {
                throw new ArgumentNullException("campaignID is a required property for WTStaticVoucher and cannot be null");
            }
            this.CampaignID = campaignID;
            this.OfferAmountCents = offerAmountCents;
            this.OrderNumber = orderNumber;
            this.TransactionType = transactionType;
            // to ensure "registerID" is required (not null)
            if (registerID == null)
            {
                throw new ArgumentNullException("registerID is a required property for WTStaticVoucher and cannot be null");
            }
            this.RegisterID = registerID;
            // to ensure "redeemedSource" is required (not null)
            if (redeemedSource == null)
            {
                throw new ArgumentNullException("redeemedSource is a required property for WTStaticVoucher and cannot be null");
            }
            this.RedeemedSource = redeemedSource;
            // to ensure "redeemedTransactionID" is required (not null)
            if (redeemedTransactionID == null)
            {
                throw new ArgumentNullException("redeemedTransactionID is a required property for WTStaticVoucher and cannot be null");
            }
            this.RedeemedTransactionID = redeemedTransactionID;
            this.RedeemedAmount = redeemedAmount;
            this.IsRedeemed = isRedeemed;
            // to ensure "refundedTransactionID" is required (not null)
            if (refundedTransactionID == null)
            {
                throw new ArgumentNullException("refundedTransactionID is a required property for WTStaticVoucher and cannot be null");
            }
            this.RefundedTransactionID = refundedTransactionID;
            this.RefundedAmount = refundedAmount;
            this.Status = status;
            // to ensure "authorizedAgainstCheckNumber" is required (not null)
            if (authorizedAgainstCheckNumber == null)
            {
                throw new ArgumentNullException("authorizedAgainstCheckNumber is a required property for WTStaticVoucher and cannot be null");
            }
            this.AuthorizedAgainstCheckNumber = authorizedAgainstCheckNumber;
            this.AuthorizedAmount = authorizedAmount;
            // to ensure "merchantID" is required (not null)
            if (merchantID == null)
            {
                throw new ArgumentNullException("merchantID is a required property for WTStaticVoucher and cannot be null");
            }
            this.MerchantID = merchantID;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.IsActive = isActive;
            // to ensure "authorizedAmountDecimal" is required (not null)
            if (authorizedAmountDecimal == null)
            {
                throw new ArgumentNullException("authorizedAmountDecimal is a required property for WTStaticVoucher and cannot be null");
            }
            this.AuthorizedAmountDecimal = authorizedAmountDecimal;
            // to ensure "authorizedAmountString" is required (not null)
            if (authorizedAmountString == null)
            {
                throw new ArgumentNullException("authorizedAmountString is a required property for WTStaticVoucher and cannot be null");
            }
            this.AuthorizedAmountString = authorizedAmountString;
            // to ensure "offerAmountCentsDecimal" is required (not null)
            if (offerAmountCentsDecimal == null)
            {
                throw new ArgumentNullException("offerAmountCentsDecimal is a required property for WTStaticVoucher and cannot be null");
            }
            this.OfferAmountCentsDecimal = offerAmountCentsDecimal;
            // to ensure "offerAmountCentsString" is required (not null)
            if (offerAmountCentsString == null)
            {
                throw new ArgumentNullException("offerAmountCentsString is a required property for WTStaticVoucher and cannot be null");
            }
            this.OfferAmountCentsString = offerAmountCentsString;
            // to ensure "redeemedAmountDecimal" is required (not null)
            if (redeemedAmountDecimal == null)
            {
                throw new ArgumentNullException("redeemedAmountDecimal is a required property for WTStaticVoucher and cannot be null");
            }
            this.RedeemedAmountDecimal = redeemedAmountDecimal;
            // to ensure "redeemedAmountString" is required (not null)
            if (redeemedAmountString == null)
            {
                throw new ArgumentNullException("redeemedAmountString is a required property for WTStaticVoucher and cannot be null");
            }
            this.RedeemedAmountString = redeemedAmountString;
            this.MemberID = memberID;
            this.CellPhoneNumber = cellPhoneNumber;
            this.CustomerID = customerID;
            this.DateTimeRedeemed = dateTimeRedeemed;
            this.DateTimeRefunded = dateTimeRefunded;
            this.DateTimeLastViewed = dateTimeLastViewed;
            this.ReasonInvalid = reasonInvalid;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public StaticVoucherId Id { get; set; }

        /// <summary>
        /// Gets or Sets CampaignID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "campaignID", IsRequired = true, EmitDefaultValue = true)]
        public string CampaignID { get; set; }

        /// <summary>
        /// Gets or Sets MemberID
        /// </summary>
        /*
        <example>MEM1001</example>
        */
        [DataMember(Name = "memberID", EmitDefaultValue = false)]
        public string MemberID { get; set; }

        /// <summary>
        /// Gets or Sets CellPhoneNumber
        /// </summary>
        /*
        <example>+18054052344</example>
        */
        [DataMember(Name = "cellPhoneNumber", EmitDefaultValue = false)]
        public string CellPhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets OfferAmountCents
        /// </summary>
        /*
        <example>5400</example>
        */
        [DataMember(Name = "offerAmountCents", IsRequired = true, EmitDefaultValue = true)]
        public int OfferAmountCents { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>
        /*
        <example>20</example>
        */
        [DataMember(Name = "orderNumber", IsRequired = true, EmitDefaultValue = true)]
        public int OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets RegisterID
        /// </summary>
        [DataMember(Name = "registerID", IsRequired = true, EmitDefaultValue = true)]
        public PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID RegisterID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedSource
        /// </summary>
        /*
        <example>AN-47</example>
        */
        [DataMember(Name = "redeemedSource", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedSource { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "redeemedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmount
        /// </summary>
        /*
        <example>540</example>
        */
        [DataMember(Name = "redeemedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RedeemedAmount { get; set; }

        /// <summary>
        /// Gets or Sets IsRedeemed
        /// </summary>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isRedeemed", IsRequired = true, EmitDefaultValue = true)]
        public bool IsRedeemed { get; set; }

        /// <summary>
        /// Gets or Sets RefundedTransactionID
        /// </summary>
        /*
        <example>Jqkaurn28170dh1fh</example>
        */
        [DataMember(Name = "refundedTransactionID", IsRequired = true, EmitDefaultValue = true)]
        public string RefundedTransactionID { get; set; }

        /// <summary>
        /// Gets or Sets RefundedAmount
        /// </summary>
        /*
        <example>540</example>
        */
        [DataMember(Name = "refundedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int RefundedAmount { get; set; }

        /// <summary>
        /// Gets or Sets CustomerID
        /// </summary>
        /*
        <example>CUST-1001</example>
        */
        [DataMember(Name = "customerID", EmitDefaultValue = false)]
        public string CustomerID { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAgainstCheckNumber
        /// </summary>
        /*
        <example>82jSUWKFLjgaj827</example>
        */
        [DataMember(Name = "authorizedAgainstCheckNumber", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAgainstCheckNumber { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmount
        /// </summary>
        /*
        <example>520</example>
        */
        [DataMember(Name = "authorizedAmount", IsRequired = true, EmitDefaultValue = true)]
        public int AuthorizedAmount { get; set; }

        /// <summary>
        /// Gets or Sets MerchantID
        /// </summary>
        /*
        <example>ueJDL982Hs</example>
        */
        [DataMember(Name = "merchantID", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantID { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmountDecimal
        /// </summary>
        /*
        <example>12.52</example>
        */
        [DataMember(Name = "authorizedAmount_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAmountDecimal { get; set; }

        /// <summary>
        /// Gets or Sets AuthorizedAmountString
        /// </summary>
        /*
        <example>$12.52</example>
        */
        [DataMember(Name = "authorizedAmount_string", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizedAmountString { get; set; }

        /// <summary>
        /// Gets or Sets OfferAmountCentsDecimal
        /// </summary>
        /*
        <example>12.52</example>
        */
        [DataMember(Name = "offerAmountCents_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string OfferAmountCentsDecimal { get; set; }

        /// <summary>
        /// Gets or Sets OfferAmountCentsString
        /// </summary>
        /*
        <example>$12.52</example>
        */
        [DataMember(Name = "offerAmountCents_string", IsRequired = true, EmitDefaultValue = true)]
        public string OfferAmountCentsString { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountDecimal
        /// </summary>
        /*
        <example>12.52</example>
        */
        [DataMember(Name = "redeemedAmount_decimal", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountDecimal { get; set; }

        /// <summary>
        /// Gets or Sets RedeemedAmountString
        /// </summary>
        /*
        <example>$12.52</example>
        */
        [DataMember(Name = "redeemedAmount_string", IsRequired = true, EmitDefaultValue = true)]
        public string RedeemedAmountString { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeRedeemed
        /// </summary>
        /*
        <example>2016-06-22 19:10:25-07</example>
        */
        [DataMember(Name = "dateTimeRedeemed", EmitDefaultValue = false)]
        public DateTime DateTimeRedeemed { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeRefunded
        /// </summary>
        /*
        <example>2016-06-22 20:10:25-07</example>
        */
        [DataMember(Name = "dateTimeRefunded", EmitDefaultValue = false)]
        public DateTime DateTimeRefunded { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeLastViewed
        /// </summary>
        /*
        <example>2016-06-21 20:10:25-07</example>
        */
        [DataMember(Name = "dateTimeLastViewed", EmitDefaultValue = false)]
        public DateTime DateTimeLastViewed { get; set; }

        /// <summary>
        /// Gets or Sets ReasonInvalid
        /// </summary>
        /*
        <example>Voucher already redeemed.</example>
        */
        [DataMember(Name = "reasonInvalid", EmitDefaultValue = false)]
        public string ReasonInvalid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WTStaticVoucher {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CampaignID: ").Append(CampaignID).Append("\n");
            sb.Append("  MemberID: ").Append(MemberID).Append("\n");
            sb.Append("  CellPhoneNumber: ").Append(CellPhoneNumber).Append("\n");
            sb.Append("  OfferAmountCents: ").Append(OfferAmountCents).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  RegisterID: ").Append(RegisterID).Append("\n");
            sb.Append("  RedeemedSource: ").Append(RedeemedSource).Append("\n");
            sb.Append("  RedeemedTransactionID: ").Append(RedeemedTransactionID).Append("\n");
            sb.Append("  RedeemedAmount: ").Append(RedeemedAmount).Append("\n");
            sb.Append("  IsRedeemed: ").Append(IsRedeemed).Append("\n");
            sb.Append("  RefundedTransactionID: ").Append(RefundedTransactionID).Append("\n");
            sb.Append("  RefundedAmount: ").Append(RefundedAmount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CustomerID: ").Append(CustomerID).Append("\n");
            sb.Append("  AuthorizedAgainstCheckNumber: ").Append(AuthorizedAgainstCheckNumber).Append("\n");
            sb.Append("  AuthorizedAmount: ").Append(AuthorizedAmount).Append("\n");
            sb.Append("  MerchantID: ").Append(MerchantID).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  AuthorizedAmountDecimal: ").Append(AuthorizedAmountDecimal).Append("\n");
            sb.Append("  AuthorizedAmountString: ").Append(AuthorizedAmountString).Append("\n");
            sb.Append("  OfferAmountCentsDecimal: ").Append(OfferAmountCentsDecimal).Append("\n");
            sb.Append("  OfferAmountCentsString: ").Append(OfferAmountCentsString).Append("\n");
            sb.Append("  RedeemedAmountDecimal: ").Append(RedeemedAmountDecimal).Append("\n");
            sb.Append("  RedeemedAmountString: ").Append(RedeemedAmountString).Append("\n");
            sb.Append("  DateTimeRedeemed: ").Append(DateTimeRedeemed).Append("\n");
            sb.Append("  DateTimeRefunded: ").Append(DateTimeRefunded).Append("\n");
            sb.Append("  DateTimeLastViewed: ").Append(DateTimeLastViewed).Append("\n");
            sb.Append("  ReasonInvalid: ").Append(ReasonInvalid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CampaignID (string) maxLength
            if (this.CampaignID != null && this.CampaignID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for CampaignID, length must be less than 10.", new [] { "CampaignID" });
            }

            // CampaignID (string) minLength
            if (this.CampaignID != null && this.CampaignID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for CampaignID, length must be greater than 10.", new [] { "CampaignID" });
            }

            if (this.CampaignID != null) {
                // CampaignID (string) pattern
                Regex regexCampaignID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexCampaignID.Match(this.CampaignID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CampaignID, must match a pattern of " + regexCampaignID, new [] { "CampaignID" });
                }
            }

            if (this.MemberID != null) {
                // MemberID (string) pattern
                Regex regexMemberID = new Regex(@"^[a-zA-Z0-9]*$", RegexOptions.CultureInvariant);
                if (!regexMemberID.Match(this.MemberID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MemberID, must match a pattern of " + regexMemberID, new [] { "MemberID" });
                }
            }

            // OfferAmountCents (int) minimum
            if (this.OfferAmountCents < (int)0)
            {
                yield return new ValidationResult("Invalid value for OfferAmountCents, must be a value greater than or equal to 0.", new [] { "OfferAmountCents" });
            }

            // OrderNumber (int) minimum
            if (this.OrderNumber < (int)0)
            {
                yield return new ValidationResult("Invalid value for OrderNumber, must be a value greater than or equal to 0.", new [] { "OrderNumber" });
            }

            // RedeemedAmount (int) minimum
            if (this.RedeemedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RedeemedAmount, must be a value greater than or equal to 0.", new [] { "RedeemedAmount" });
            }

            // RefundedAmount (int) minimum
            if (this.RefundedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundedAmount, must be a value greater than or equal to 0.", new [] { "RefundedAmount" });
            }

            // AuthorizedAmount (int) minimum
            if (this.AuthorizedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for AuthorizedAmount, must be a value greater than or equal to 0.", new [] { "AuthorizedAmount" });
            }

            // MerchantID (string) maxLength
            if (this.MerchantID != null && this.MerchantID.Length > 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be less than 10.", new [] { "MerchantID" });
            }

            // MerchantID (string) minLength
            if (this.MerchantID != null && this.MerchantID.Length < 10)
            {
                yield return new ValidationResult("Invalid value for MerchantID, length must be greater than 10.", new [] { "MerchantID" });
            }

            if (this.MerchantID != null) {
                // MerchantID (string) pattern
                Regex regexMerchantID = new Regex(@"^[a-zA-Z0-9]+$", RegexOptions.CultureInvariant);
                if (!regexMerchantID.Match(this.MerchantID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MerchantID, must match a pattern of " + regexMerchantID, new [] { "MerchantID" });
                }
            }

            yield break;
        }
    }

}
