/*
 * wallet-api
 *
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T08:20:50.386Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using WalletInc.Client;
using WalletInc.Model;

namespace WalletInc.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMembershipTiersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Archive Membership Tier
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        WTMembershipTier ArchiveMembershipTier(string id);

        /// <summary>
        /// Archive Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        ApiResponse<WTMembershipTier> ArchiveMembershipTierWithHttpInfo(string id);
        /// <summary>
        /// Create Membership Tier
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <returns>WTMembershipTier</returns>
        WTMembershipTier CreateMembershipTier(WTMembershipTierCreationParams wTMembershipTierCreationParams);

        /// <summary>
        /// Create Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        ApiResponse<WTMembershipTier> CreateMembershipTierWithHttpInfo(WTMembershipTierCreationParams wTMembershipTierCreationParams);
        /// <summary>
        /// Get all Membership Tiers
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>List&lt;WTMembershipTier&gt;</returns>
        List<WTMembershipTier> FetchAllMembershipTiers(bool? isArchiveIncluded = default);

        /// <summary>
        /// Get all Membership Tiers
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>ApiResponse of List&lt;WTMembershipTier&gt;</returns>
        ApiResponse<List<WTMembershipTier>> FetchAllMembershipTiersWithHttpInfo(bool? isArchiveIncluded = default);
        /// <summary>
        /// Get all Membership Tiers with member count
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        List<WTMembershipTierWithMemberCount> FetchAllMembershipTiersWithMemberCount(bool? isArchiveIncluded = default);

        /// <summary>
        /// Get all Membership Tiers with member count
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>ApiResponse of List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        ApiResponse<List<WTMembershipTierWithMemberCount>> FetchAllMembershipTiersWithMemberCountWithHttpInfo(bool? isArchiveIncluded = default);
        /// <summary>
        /// Get Membership Tier
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        WTMembershipTier FetchMembershipTierById(string id);

        /// <summary>
        /// Get Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        ApiResponse<WTMembershipTier> FetchMembershipTierByIdWithHttpInfo(string id);
        /// <summary>
        /// Get Membership Tier history
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>MSMembershipTierHistoryPagination</returns>
        MSMembershipTierHistoryPagination FetchMembershipTierHistoryLog(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions);

        /// <summary>
        /// Get Membership Tier history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>ApiResponse of MSMembershipTierHistoryPagination</returns>
        ApiResponse<MSMembershipTierHistoryPagination> FetchMembershipTierHistoryLogWithHttpInfo(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions);
        /// <summary>
        /// Get Membership Tier redemption log
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>MSMembershipTierRedemptionPagination</returns>
        MSMembershipTierRedemptionPagination FetchMembershipTierRedemptionLog(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions);

        /// <summary>
        /// Get Membership Tier redemption log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>ApiResponse of MSMembershipTierRedemptionPagination</returns>
        ApiResponse<MSMembershipTierRedemptionPagination> FetchMembershipTierRedemptionLogWithHttpInfo(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions);
        /// <summary>
        /// Restore Membership Tier
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        WTMembershipTier RestoreMembershipTier(string id);

        /// <summary>
        /// Restore Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        ApiResponse<WTMembershipTier> RestoreMembershipTierWithHttpInfo(string id);
        /// <summary>
        /// Update Membership Tier
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <returns>WTMembershipTier</returns>
        WTMembershipTier UpdateMembershipTier(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams);

        /// <summary>
        /// Update Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        ApiResponse<WTMembershipTier> UpdateMembershipTierWithHttpInfo(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMembershipTiersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Archive Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        System.Threading.Tasks.Task<WTMembershipTier> ArchiveMembershipTierAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Archive Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        System.Threading.Tasks.Task<ApiResponse<WTMembershipTier>> ArchiveMembershipTierWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        System.Threading.Tasks.Task<WTMembershipTier> CreateMembershipTierAsync(WTMembershipTierCreationParams wTMembershipTierCreationParams, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        System.Threading.Tasks.Task<ApiResponse<WTMembershipTier>> CreateMembershipTierWithHttpInfoAsync(WTMembershipTierCreationParams wTMembershipTierCreationParams, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get all Membership Tiers
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;WTMembershipTier&gt;</returns>
        System.Threading.Tasks.Task<List<WTMembershipTier>> FetchAllMembershipTiersAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all Membership Tiers
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;WTMembershipTier&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<WTMembershipTier>>> FetchAllMembershipTiersWithHttpInfoAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get all Membership Tiers with member count
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        System.Threading.Tasks.Task<List<WTMembershipTierWithMemberCount>> FetchAllMembershipTiersWithMemberCountAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all Membership Tiers with member count
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;WTMembershipTierWithMemberCount&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<WTMembershipTierWithMemberCount>>> FetchAllMembershipTiersWithMemberCountWithHttpInfoAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        System.Threading.Tasks.Task<WTMembershipTier> FetchMembershipTierByIdAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        System.Threading.Tasks.Task<ApiResponse<WTMembershipTier>> FetchMembershipTierByIdWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Membership Tier history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MSMembershipTierHistoryPagination</returns>
        System.Threading.Tasks.Task<MSMembershipTierHistoryPagination> FetchMembershipTierHistoryLogAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Membership Tier history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MSMembershipTierHistoryPagination)</returns>
        System.Threading.Tasks.Task<ApiResponse<MSMembershipTierHistoryPagination>> FetchMembershipTierHistoryLogWithHttpInfoAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Membership Tier redemption log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MSMembershipTierRedemptionPagination</returns>
        System.Threading.Tasks.Task<MSMembershipTierRedemptionPagination> FetchMembershipTierRedemptionLogAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Membership Tier redemption log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MSMembershipTierRedemptionPagination)</returns>
        System.Threading.Tasks.Task<ApiResponse<MSMembershipTierRedemptionPagination>> FetchMembershipTierRedemptionLogWithHttpInfoAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Restore Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        System.Threading.Tasks.Task<WTMembershipTier> RestoreMembershipTierAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Restore Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        System.Threading.Tasks.Task<ApiResponse<WTMembershipTier>> RestoreMembershipTierWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        System.Threading.Tasks.Task<WTMembershipTier> UpdateMembershipTierAsync(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update Membership Tier
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        System.Threading.Tasks.Task<ApiResponse<WTMembershipTier>> UpdateMembershipTierWithHttpInfoAsync(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMembershipTiersApi : IMembershipTiersApiSync, IMembershipTiersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MembershipTiersApi : IDisposable, IMembershipTiersApi
    {
        private WalletInc.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MembershipTiersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MembershipTiersApi(string basePath)
        {
            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                new WalletInc.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new WalletInc.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MembershipTiersApi(WalletInc.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new WalletInc.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MembershipTiersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MembershipTiersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                new WalletInc.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new WalletInc.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MembershipTiersApi(HttpClient client, WalletInc.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new WalletInc.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MembershipTiersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MembershipTiersApi(WalletInc.Client.ISynchronousClient client, WalletInc.Client.IAsynchronousClient asyncClient, WalletInc.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public WalletInc.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public WalletInc.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public WalletInc.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public WalletInc.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public WalletInc.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Archive Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        public WTMembershipTier ArchiveMembershipTier(string id)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = ArchiveMembershipTierWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Archive Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        public WalletInc.Client.ApiResponse<WTMembershipTier> ArchiveMembershipTierWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->ArchiveMembershipTier");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ArchiveMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Archive Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        public async System.Threading.Tasks.Task<WTMembershipTier> ArchiveMembershipTierAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = await ArchiveMembershipTierWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Archive Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<WTMembershipTier>> ArchiveMembershipTierWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->ArchiveMembershipTier");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ArchiveMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <returns>WTMembershipTier</returns>
        public WTMembershipTier CreateMembershipTier(WTMembershipTierCreationParams wTMembershipTierCreationParams)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = CreateMembershipTierWithHttpInfo(wTMembershipTierCreationParams);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        public WalletInc.Client.ApiResponse<WTMembershipTier> CreateMembershipTierWithHttpInfo(WTMembershipTierCreationParams wTMembershipTierCreationParams)
        {
            // verify the required parameter 'wTMembershipTierCreationParams' is set
            if (wTMembershipTierCreationParams == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'wTMembershipTierCreationParams' when calling MembershipTiersApi->CreateMembershipTier");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = wTMembershipTierCreationParams;


            // make the HTTP request
            var localVarResponse = this.Client.Post<WTMembershipTier>("/v2/membership/tier", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        public async System.Threading.Tasks.Task<WTMembershipTier> CreateMembershipTierAsync(WTMembershipTierCreationParams wTMembershipTierCreationParams, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = await CreateMembershipTierWithHttpInfoAsync(wTMembershipTierCreationParams, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="wTMembershipTierCreationParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<WTMembershipTier>> CreateMembershipTierWithHttpInfoAsync(WTMembershipTierCreationParams wTMembershipTierCreationParams, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'wTMembershipTierCreationParams' is set
            if (wTMembershipTierCreationParams == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'wTMembershipTierCreationParams' when calling MembershipTiersApi->CreateMembershipTier");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = wTMembershipTierCreationParams;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<WTMembershipTier>("/v2/membership/tier", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all Membership Tiers 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>List&lt;WTMembershipTier&gt;</returns>
        public List<WTMembershipTier> FetchAllMembershipTiers(bool? isArchiveIncluded = default)
        {
            WalletInc.Client.ApiResponse<List<WTMembershipTier>> localVarResponse = FetchAllMembershipTiersWithHttpInfo(isArchiveIncluded);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Membership Tiers 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>ApiResponse of List&lt;WTMembershipTier&gt;</returns>
        public WalletInc.Client.ApiResponse<List<WTMembershipTier>> FetchAllMembershipTiersWithHttpInfo(bool? isArchiveIncluded = default)
        {
            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (isArchiveIncluded != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "isArchiveIncluded", isArchiveIncluded));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<WTMembershipTier>>("/v2/membership/tier/all", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllMembershipTiers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all Membership Tiers 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;WTMembershipTier&gt;</returns>
        public async System.Threading.Tasks.Task<List<WTMembershipTier>> FetchAllMembershipTiersAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<List<WTMembershipTier>> localVarResponse = await FetchAllMembershipTiersWithHttpInfoAsync(isArchiveIncluded, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Membership Tiers 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;WTMembershipTier&gt;)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<List<WTMembershipTier>>> FetchAllMembershipTiersWithHttpInfoAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default)
        {

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (isArchiveIncluded != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "isArchiveIncluded", isArchiveIncluded));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<WTMembershipTier>>("/v2/membership/tier/all", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllMembershipTiers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all Membership Tiers with member count 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        public List<WTMembershipTierWithMemberCount> FetchAllMembershipTiersWithMemberCount(bool? isArchiveIncluded = default)
        {
            WalletInc.Client.ApiResponse<List<WTMembershipTierWithMemberCount>> localVarResponse = FetchAllMembershipTiersWithMemberCountWithHttpInfo(isArchiveIncluded);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Membership Tiers with member count 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <returns>ApiResponse of List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        public WalletInc.Client.ApiResponse<List<WTMembershipTierWithMemberCount>> FetchAllMembershipTiersWithMemberCountWithHttpInfo(bool? isArchiveIncluded = default)
        {
            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (isArchiveIncluded != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "isArchiveIncluded", isArchiveIncluded));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<WTMembershipTierWithMemberCount>>("/v2/membership/tier/allWithMemberCount", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllMembershipTiersWithMemberCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all Membership Tiers with member count 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;WTMembershipTierWithMemberCount&gt;</returns>
        public async System.Threading.Tasks.Task<List<WTMembershipTierWithMemberCount>> FetchAllMembershipTiersWithMemberCountAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<List<WTMembershipTierWithMemberCount>> localVarResponse = await FetchAllMembershipTiersWithMemberCountWithHttpInfoAsync(isArchiveIncluded, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Membership Tiers with member count 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="isArchiveIncluded"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;WTMembershipTierWithMemberCount&gt;)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<List<WTMembershipTierWithMemberCount>>> FetchAllMembershipTiersWithMemberCountWithHttpInfoAsync(bool? isArchiveIncluded = default, System.Threading.CancellationToken cancellationToken = default)
        {

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (isArchiveIncluded != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "isArchiveIncluded", isArchiveIncluded));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<WTMembershipTierWithMemberCount>>("/v2/membership/tier/allWithMemberCount", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllMembershipTiersWithMemberCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        public WTMembershipTier FetchMembershipTierById(string id)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = FetchMembershipTierByIdWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        public WalletInc.Client.ApiResponse<WTMembershipTier> FetchMembershipTierByIdWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->FetchMembershipTierById");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        public async System.Threading.Tasks.Task<WTMembershipTier> FetchMembershipTierByIdAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = await FetchMembershipTierByIdWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<WTMembershipTier>> FetchMembershipTierByIdWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->FetchMembershipTierById");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier history 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>MSMembershipTierHistoryPagination</returns>
        public MSMembershipTierHistoryPagination FetchMembershipTierHistoryLog(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions)
        {
            WalletInc.Client.ApiResponse<MSMembershipTierHistoryPagination> localVarResponse = FetchMembershipTierHistoryLogWithHttpInfo(paginationRequestWithIDAndWithoutSortOptions);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier history 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>ApiResponse of MSMembershipTierHistoryPagination</returns>
        public WalletInc.Client.ApiResponse<MSMembershipTierHistoryPagination> FetchMembershipTierHistoryLogWithHttpInfo(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions)
        {
            // verify the required parameter 'paginationRequestWithIDAndWithoutSortOptions' is set
            if (paginationRequestWithIDAndWithoutSortOptions == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'paginationRequestWithIDAndWithoutSortOptions' when calling MembershipTiersApi->FetchMembershipTierHistoryLog");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = paginationRequestWithIDAndWithoutSortOptions;


            // make the HTTP request
            var localVarResponse = this.Client.Post<MSMembershipTierHistoryPagination>("/v2/membership/tier/history/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierHistoryLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier history 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MSMembershipTierHistoryPagination</returns>
        public async System.Threading.Tasks.Task<MSMembershipTierHistoryPagination> FetchMembershipTierHistoryLogAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<MSMembershipTierHistoryPagination> localVarResponse = await FetchMembershipTierHistoryLogWithHttpInfoAsync(paginationRequestWithIDAndWithoutSortOptions, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier history 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MSMembershipTierHistoryPagination)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<MSMembershipTierHistoryPagination>> FetchMembershipTierHistoryLogWithHttpInfoAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'paginationRequestWithIDAndWithoutSortOptions' is set
            if (paginationRequestWithIDAndWithoutSortOptions == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'paginationRequestWithIDAndWithoutSortOptions' when calling MembershipTiersApi->FetchMembershipTierHistoryLog");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = paginationRequestWithIDAndWithoutSortOptions;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MSMembershipTierHistoryPagination>("/v2/membership/tier/history/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierHistoryLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier redemption log 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>MSMembershipTierRedemptionPagination</returns>
        public MSMembershipTierRedemptionPagination FetchMembershipTierRedemptionLog(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions)
        {
            WalletInc.Client.ApiResponse<MSMembershipTierRedemptionPagination> localVarResponse = FetchMembershipTierRedemptionLogWithHttpInfo(paginationRequestWithIDAndWithoutSortOptions);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier redemption log 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <returns>ApiResponse of MSMembershipTierRedemptionPagination</returns>
        public WalletInc.Client.ApiResponse<MSMembershipTierRedemptionPagination> FetchMembershipTierRedemptionLogWithHttpInfo(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions)
        {
            // verify the required parameter 'paginationRequestWithIDAndWithoutSortOptions' is set
            if (paginationRequestWithIDAndWithoutSortOptions == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'paginationRequestWithIDAndWithoutSortOptions' when calling MembershipTiersApi->FetchMembershipTierRedemptionLog");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = paginationRequestWithIDAndWithoutSortOptions;


            // make the HTTP request
            var localVarResponse = this.Client.Post<MSMembershipTierRedemptionPagination>("/v2/membership/tier/redemption/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierRedemptionLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Membership Tier redemption log 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MSMembershipTierRedemptionPagination</returns>
        public async System.Threading.Tasks.Task<MSMembershipTierRedemptionPagination> FetchMembershipTierRedemptionLogAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<MSMembershipTierRedemptionPagination> localVarResponse = await FetchMembershipTierRedemptionLogWithHttpInfoAsync(paginationRequestWithIDAndWithoutSortOptions, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Membership Tier redemption log 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paginationRequestWithIDAndWithoutSortOptions"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MSMembershipTierRedemptionPagination)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<MSMembershipTierRedemptionPagination>> FetchMembershipTierRedemptionLogWithHttpInfoAsync(PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'paginationRequestWithIDAndWithoutSortOptions' is set
            if (paginationRequestWithIDAndWithoutSortOptions == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'paginationRequestWithIDAndWithoutSortOptions' when calling MembershipTiersApi->FetchMembershipTierRedemptionLog");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = paginationRequestWithIDAndWithoutSortOptions;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MSMembershipTierRedemptionPagination>("/v2/membership/tier/redemption/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchMembershipTierRedemptionLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Restore Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>WTMembershipTier</returns>
        public WTMembershipTier RestoreMembershipTier(string id)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = RestoreMembershipTierWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Restore Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        public WalletInc.Client.ApiResponse<WTMembershipTier> RestoreMembershipTierWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->RestoreMembershipTier");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Patch<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RestoreMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Restore Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        public async System.Threading.Tasks.Task<WTMembershipTier> RestoreMembershipTierAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = await RestoreMembershipTierWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Restore Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<WTMembershipTier>> RestoreMembershipTierWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->RestoreMembershipTier");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RestoreMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <returns>WTMembershipTier</returns>
        public WTMembershipTier UpdateMembershipTier(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = UpdateMembershipTierWithHttpInfo(id, wTMembershipTierUpdateParams);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <returns>ApiResponse of WTMembershipTier</returns>
        public WalletInc.Client.ApiResponse<WTMembershipTier> UpdateMembershipTierWithHttpInfo(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->UpdateMembershipTier");

            // verify the required parameter 'wTMembershipTierUpdateParams' is set
            if (wTMembershipTierUpdateParams == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'wTMembershipTierUpdateParams' when calling MembershipTiersApi->UpdateMembershipTier");

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = wTMembershipTierUpdateParams;


            // make the HTTP request
            var localVarResponse = this.Client.Put<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WTMembershipTier</returns>
        public async System.Threading.Tasks.Task<WTMembershipTier> UpdateMembershipTierAsync(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<WTMembershipTier> localVarResponse = await UpdateMembershipTierWithHttpInfoAsync(id, wTMembershipTierUpdateParams, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Membership Tier 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="wTMembershipTierUpdateParams"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WTMembershipTier)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<WTMembershipTier>> UpdateMembershipTierWithHttpInfoAsync(string id, WTMembershipTierUpdateParams wTMembershipTierUpdateParams, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'id' when calling MembershipTiersApi->UpdateMembershipTier");

            // verify the required parameter 'wTMembershipTierUpdateParams' is set
            if (wTMembershipTierUpdateParams == null)
                throw new WalletInc.Client.ApiException(400, "Missing required parameter 'wTMembershipTierUpdateParams' when calling MembershipTiersApi->UpdateMembershipTier");


            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", WalletInc.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = wTMembershipTierUpdateParams;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<WTMembershipTier>("/v2/membership/tier/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateMembershipTier", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
