/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using WalletInc.Client;
using WalletInc.Model;

namespace WalletInc.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWalletTransactionLedgerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get ledger entries
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <returns>FetchAllLedgerTransactions200Response</returns>
        FetchAllLedgerTransactions200Response FetchAllLedgerTransactions(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default);

        /// <summary>
        /// Get ledger entries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <returns>ApiResponse of FetchAllLedgerTransactions200Response</returns>
        ApiResponse<FetchAllLedgerTransactions200Response> FetchAllLedgerTransactionsWithHttpInfo(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWalletTransactionLedgerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get ledger entries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FetchAllLedgerTransactions200Response</returns>
        System.Threading.Tasks.Task<FetchAllLedgerTransactions200Response> FetchAllLedgerTransactionsAsync(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get ledger entries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FetchAllLedgerTransactions200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<FetchAllLedgerTransactions200Response>> FetchAllLedgerTransactionsWithHttpInfoAsync(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWalletTransactionLedgerApi : IWalletTransactionLedgerApiSync, IWalletTransactionLedgerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WalletTransactionLedgerApi : IDisposable, IWalletTransactionLedgerApi
    {
        private WalletInc.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public WalletTransactionLedgerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public WalletTransactionLedgerApi(string basePath)
        {
            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                new WalletInc.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new WalletInc.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public WalletTransactionLedgerApi(WalletInc.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new WalletInc.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WalletTransactionLedgerApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WalletTransactionLedgerApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                new WalletInc.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new WalletInc.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WalletTransactionLedgerApi(HttpClient client, WalletInc.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = WalletInc.Client.Configuration.MergeConfigurations(
                WalletInc.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new WalletInc.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransactionLedgerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public WalletTransactionLedgerApi(WalletInc.Client.ISynchronousClient client, WalletInc.Client.IAsynchronousClient asyncClient, WalletInc.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = WalletInc.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public WalletInc.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public WalletInc.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public WalletInc.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public WalletInc.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public WalletInc.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get ledger entries 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <returns>FetchAllLedgerTransactions200Response</returns>
        public FetchAllLedgerTransactions200Response FetchAllLedgerTransactions(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default)
        {
            WalletInc.Client.ApiResponse<FetchAllLedgerTransactions200Response> localVarResponse = FetchAllLedgerTransactionsWithHttpInfo(startDateTime, endDateTime, pageNum, pageSize, registerType);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get ledger entries 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <returns>ApiResponse of FetchAllLedgerTransactions200Response</returns>
        public WalletInc.Client.ApiResponse<FetchAllLedgerTransactions200Response> FetchAllLedgerTransactionsWithHttpInfo(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default)
        {
            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "startDateTime", startDateTime));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "endDateTime", endDateTime));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "pageNum", pageNum));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            if (registerType != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "registerType", registerType));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<FetchAllLedgerTransactions200Response>("/v2/pos/ledger/transactions/all", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllLedgerTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get ledger entries 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FetchAllLedgerTransactions200Response</returns>
        public async System.Threading.Tasks.Task<FetchAllLedgerTransactions200Response> FetchAllLedgerTransactionsAsync(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            WalletInc.Client.ApiResponse<FetchAllLedgerTransactions200Response> localVarResponse = await FetchAllLedgerTransactionsWithHttpInfoAsync(startDateTime, endDateTime, pageNum, pageSize, registerType, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get ledger entries 
        /// </summary>
        /// <exception cref="WalletInc.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDateTime"></param>
        /// <param name="endDateTime"></param>
        /// <param name="pageNum"></param>
        /// <param name="pageSize"></param>
        /// <param name="registerType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FetchAllLedgerTransactions200Response)</returns>
        public async System.Threading.Tasks.Task<WalletInc.Client.ApiResponse<FetchAllLedgerTransactions200Response>> FetchAllLedgerTransactionsWithHttpInfoAsync(DateTime startDateTime, DateTime endDateTime, double pageNum, double pageSize, ApplicableTerminals? registerType = default, System.Threading.CancellationToken cancellationToken = default)
        {

            WalletInc.Client.RequestOptions localVarRequestOptions = new WalletInc.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = WalletInc.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = WalletInc.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "startDateTime", startDateTime));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "endDateTime", endDateTime));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "pageNum", pageNum));
            localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            if (registerType != null)
            {
                localVarRequestOptions.QueryParameters.Add(WalletInc.Client.ClientUtils.ParameterToMultiMap("", "registerType", registerType));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<FetchAllLedgerTransactions200Response>("/v2/pos/ledger/transactions/all", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FetchAllLedgerTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
