/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing APIKeysApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class APIKeysApiTests : IDisposable
    {
        private APIKeysApi instance;

        public APIKeysApiTests()
        {
            instance = new APIKeysApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APIKeysApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' APIKeysApi
            //Assert.IsType<APIKeysApi>(instance);
        }

        /// <summary>
        /// Test ArchiveEmployeeAPIKeys
        /// </summary>
        [Fact]
        public void ArchiveEmployeeAPIKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ArchiveEmployeeAPIKeys(id);
            //Assert.IsType<EmployeeAPIKey>(response);
        }

        /// <summary>
        /// Test CreateEmployeeAPIKeys
        /// </summary>
        [Fact]
        public void CreateEmployeeAPIKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmployeeAPIKeyCreateParams wTEmployeeAPIKeyCreateParams = null;
            //var response = instance.CreateEmployeeAPIKeys(wTEmployeeAPIKeyCreateParams);
            //Assert.IsType<EmployeeAPIKey>(response);
        }

        /// <summary>
        /// Test FetchAllEmployeeAPIKeys
        /// </summary>
        [Fact]
        public void FetchAllEmployeeAPIKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? isArchiveIncluded = null;
            //var response = instance.FetchAllEmployeeAPIKeys(isArchiveIncluded);
            //Assert.IsType<List<EmployeeAPIKey>>(response);
        }

        /// <summary>
        /// Test FetchEmployeeAPIKeyById
        /// </summary>
        [Fact]
        public void FetchEmployeeAPIKeyByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.FetchEmployeeAPIKeyById(id);
            //Assert.IsType<WTEmployeeAPIKey>(response);
        }

        /// <summary>
        /// Test UpdateEmployeeAPIKeys
        /// </summary>
        [Fact]
        public void UpdateEmployeeAPIKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //WTEmployeeAPIKeyUpdateParams wTEmployeeAPIKeyUpdateParams = null;
            //var response = instance.UpdateEmployeeAPIKeys(id, wTEmployeeAPIKeyUpdateParams);
            //Assert.IsType<EmployeeAPIKey>(response);
        }
    }
}
