/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing AppToPersonA2PRegistrationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AppToPersonA2PRegistrationApiTests : IDisposable
    {
        private AppToPersonA2PRegistrationApi instance;

        public AppToPersonA2PRegistrationApiTests()
        {
            instance = new AppToPersonA2PRegistrationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppToPersonA2PRegistrationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AppToPersonA2PRegistrationApi
            //Assert.IsType<AppToPersonA2PRegistrationApi>(instance);
        }

        /// <summary>
        /// Test BeginA2PApplication
        /// </summary>
        [Fact]
        public void BeginA2PApplicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //A2PApplicationSubmission a2PApplicationSubmission = null;
            //var response = instance.BeginA2PApplication(a2PApplicationSubmission);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test FetchA2PApplication
        /// </summary>
        [Fact]
        public void FetchA2PApplicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FetchA2PApplication();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test FetchA2PRegistration
        /// </summary>
        [Fact]
        public void FetchA2PRegistrationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FetchA2PRegistration();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test UpdateA2PApplication
        /// </summary>
        [Fact]
        public void UpdateA2PApplicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string applicationID = null;
            //WTA2PApplicationUpdateParams wTA2PApplicationUpdateParams = null;
            //var response = instance.UpdateA2PApplication(applicationID, wTA2PApplicationUpdateParams);
            //Assert.IsType<bool>(response);
        }
    }
}
