/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing CountriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CountriesApiTests : IDisposable
    {
        private CountriesApi instance;

        public CountriesApiTests()
        {
            instance = new CountriesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountriesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CountriesApi
            //Assert.IsType<CountriesApi>(instance);
        }

        /// <summary>
        /// Test FetchAllCountries
        /// </summary>
        [Fact]
        public void FetchAllCountriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FetchAllCountries();
            //Assert.IsType<List<FetchAllCountries200ResponseInner>>(response);
        }
    }
}
