/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing EmailSubscribersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailSubscribersApiTests : IDisposable
    {
        private EmailSubscribersApi instance;

        public EmailSubscribersApiTests()
        {
            instance = new EmailSubscribersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailSubscribersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailSubscribersApi
            //Assert.IsType<EmailSubscribersApi>(instance);
        }

        /// <summary>
        /// Test ArchiveEmailSubscriber
        /// </summary>
        [Fact]
        public void ArchiveEmailSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ArchiveEmailSubscriber(id);
            //Assert.IsType<EmailSubscriber>(response);
        }

        /// <summary>
        /// Test CreateEmailSubscriber
        /// </summary>
        [Fact]
        public void CreateEmailSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmailSubscriberCreateParams wTEmailSubscriberCreateParams = null;
            //var response = instance.CreateEmailSubscriber(wTEmailSubscriberCreateParams);
            //Assert.IsType<EmailSubscriber>(response);
        }

        /// <summary>
        /// Test FetchAllEmailSubscribers
        /// </summary>
        [Fact]
        public void FetchAllEmailSubscribersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? startDateTime = null;
            //DateTime? endDateTime = null;
            //bool? isArchiveIncluded = null;
            //var response = instance.FetchAllEmailSubscribers(startDateTime, endDateTime, isArchiveIncluded);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test RestoreEmailSubscriber
        /// </summary>
        [Fact]
        public void RestoreEmailSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RestoreEmailSubscriber(id);
            //Assert.IsType<EmailSubscriber>(response);
        }

        /// <summary>
        /// Test UpdateEmailSubscriber
        /// </summary>
        [Fact]
        public void UpdateEmailSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //WTEmailSubscriberUpdateParams wTEmailSubscriberUpdateParams = null;
            //var response = instance.UpdateEmailSubscriber(id, wTEmailSubscriberUpdateParams);
            //Assert.IsType<EmailSubscriber>(response);
        }
    }
}
