/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing FilesDocumentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FilesDocumentsApiTests : IDisposable
    {
        private FilesDocumentsApi instance;

        public FilesDocumentsApiTests()
        {
            instance = new FilesDocumentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilesDocumentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FilesDocumentsApi
            //Assert.IsType<FilesDocumentsApi>(instance);
        }

        /// <summary>
        /// Test CreateDocument
        /// </summary>
        [Fact]
        public void CreateDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmployeeCreateDocument wTEmployeeCreateDocument = null;
            //var response = instance.CreateDocument(wTEmployeeCreateDocument);
            //Assert.IsType<Document>(response);
        }

        /// <summary>
        /// Test CreateFile
        /// </summary>
        [Fact]
        public void CreateFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmployeeFileCreate wTEmployeeFileCreate = null;
            //var response = instance.CreateFile(wTEmployeeFileCreate);
            //Assert.IsType<CreateFile200Response>(response);
        }

        /// <summary>
        /// Test CreateMediaFile
        /// </summary>
        [Fact]
        public void CreateMediaFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmployeeCreateMediaFile wTEmployeeCreateMediaFile = null;
            //var response = instance.CreateMediaFile(wTEmployeeCreateMediaFile);
            //Assert.IsType<MediaFile>(response);
        }

        /// <summary>
        /// Test DeleteDocument
        /// </summary>
        [Fact]
        public void DeleteDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string documentID = null;
            //var response = instance.DeleteDocument(documentID);
            //Assert.IsType<Document>(response);
        }

        /// <summary>
        /// Test DeleteMediaFile
        /// </summary>
        [Fact]
        public void DeleteMediaFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string mediaFileID = null;
            //var response = instance.DeleteMediaFile(mediaFileID);
            //Assert.IsType<MediaFile>(response);
        }

        /// <summary>
        /// Test DownloadFile
        /// </summary>
        [Fact]
        public void DownloadFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fileID = null;
            //var response = instance.DownloadFile(fileID);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test FailedImport
        /// </summary>
        [Fact]
        public void FailedImportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fileID = null;
            //var response = instance.FailedImport(fileID);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test FetchDocuments
        /// </summary>
        [Fact]
        public void FetchDocumentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? folder = null;
            //var response = instance.FetchDocuments(folder);
            //Assert.IsType<List<Document>>(response);
        }

        /// <summary>
        /// Test FetchMediaFiles
        /// </summary>
        [Fact]
        public void FetchMediaFilesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? folder = null;
            //var response = instance.FetchMediaFiles(folder);
            //Assert.IsType<List<MediaFile>>(response);
        }

        /// <summary>
        /// Test PresignFile
        /// </summary>
        [Fact]
        public void PresignFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTEmployeeS3FilePresign wTEmployeeS3FilePresign = null;
            //var response = instance.PresignFile(wTEmployeeS3FilePresign);
            //Assert.IsType<PresignedPost>(response);
        }
    }
}
