/*
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using WalletInc.Client;
using WalletInc.Api;
// uncomment below to import models
//using WalletInc.Model;

namespace WalletInc.Test.Api
{
    /// <summary>
    ///  Class for testing MembershipTiersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MembershipTiersApiTests : IDisposable
    {
        private MembershipTiersApi instance;

        public MembershipTiersApiTests()
        {
            instance = new MembershipTiersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MembershipTiersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MembershipTiersApi
            //Assert.IsType<MembershipTiersApi>(instance);
        }

        /// <summary>
        /// Test ArchiveMembershipTier
        /// </summary>
        [Fact]
        public void ArchiveMembershipTierTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ArchiveMembershipTier(id);
            //Assert.IsType<WTMembershipTier>(response);
        }

        /// <summary>
        /// Test CreateMembershipTier
        /// </summary>
        [Fact]
        public void CreateMembershipTierTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WTMembershipTierCreationParams wTMembershipTierCreationParams = null;
            //var response = instance.CreateMembershipTier(wTMembershipTierCreationParams);
            //Assert.IsType<WTMembershipTier>(response);
        }

        /// <summary>
        /// Test FetchAllMembershipTiers
        /// </summary>
        [Fact]
        public void FetchAllMembershipTiersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? isArchiveIncluded = null;
            //var response = instance.FetchAllMembershipTiers(isArchiveIncluded);
            //Assert.IsType<List<WTMembershipTier>>(response);
        }

        /// <summary>
        /// Test FetchAllMembershipTiersWithMemberCount
        /// </summary>
        [Fact]
        public void FetchAllMembershipTiersWithMemberCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? isArchiveIncluded = null;
            //var response = instance.FetchAllMembershipTiersWithMemberCount(isArchiveIncluded);
            //Assert.IsType<List<WTMembershipTierWithMemberCount>>(response);
        }

        /// <summary>
        /// Test FetchMembershipTierById
        /// </summary>
        [Fact]
        public void FetchMembershipTierByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.FetchMembershipTierById(id);
            //Assert.IsType<WTMembershipTier>(response);
        }

        /// <summary>
        /// Test FetchMembershipTierHistoryLog
        /// </summary>
        [Fact]
        public void FetchMembershipTierHistoryLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions = null;
            //var response = instance.FetchMembershipTierHistoryLog(paginationRequestWithIDAndWithoutSortOptions);
            //Assert.IsType<MSMembershipTierHistoryPagination>(response);
        }

        /// <summary>
        /// Test FetchMembershipTierRedemptionLog
        /// </summary>
        [Fact]
        public void FetchMembershipTierRedemptionLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PaginationRequestWithIDAndWithoutSortOptions paginationRequestWithIDAndWithoutSortOptions = null;
            //var response = instance.FetchMembershipTierRedemptionLog(paginationRequestWithIDAndWithoutSortOptions);
            //Assert.IsType<MSMembershipTierRedemptionPagination>(response);
        }

        /// <summary>
        /// Test RestoreMembershipTier
        /// </summary>
        [Fact]
        public void RestoreMembershipTierTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RestoreMembershipTier(id);
            //Assert.IsType<WTMembershipTier>(response);
        }

        /// <summary>
        /// Test UpdateMembershipTier
        /// </summary>
        [Fact]
        public void UpdateMembershipTierTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //WTMembershipTierUpdateParams wTMembershipTierUpdateParams = null;
            //var response = instance.UpdateMembershipTier(id, wTMembershipTierUpdateParams);
            //Assert.IsType<WTMembershipTier>(response);
        }
    }
}
